"""Convert the supplied artwork to a lossless zlib stream of LCD RGB565 pixels.

Requires Pillow. Run from any directory; --check verifies the checked-in asset.
"""
import argparse
import hashlib
from pathlib import Path
import zlib

from PIL import Image, ImageOps

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "doc/mimamori_sense_start_disp.png"
OUTPUT = ROOT / "e2studio_CPU0/src/ui/ui_startup_image_data.inc"


def pixels():
    with Image.open(SOURCE) as source:
        art = ImageOps.contain(source.convert("RGB"), (1024, 600), Image.Resampling.LANCZOS)
    canvas = Image.new("RGB", (1024, 600), (255, 251, 247))
    canvas.paste(art, ((1024 - art.width) // 2, (600 - art.height) // 2))
    raw = bytearray()
    for r, g, b in canvas.getdata():
        value = ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)
        raw.extend(value.to_bytes(2, "little"))
    return bytes(raw)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    raw = pixels()
    data = zlib.compress(raw, 9)
    assert zlib.decompress(data) == raw
    lines = [
        "/* Generated by scripts/startup-screen/convert_image.py. Do not edit.",
        f" * Source SHA256: {hashlib.sha256(SOURCE.read_bytes()).hexdigest()}",
        f" * RGB565 SHA256: {hashlib.sha256(raw).hexdigest()}",
        " * 1024 x 600, little-endian RGB565, zlib (DEFLATE + Adler-32).",
        " */",
        f"static const uint8_t s_image_zlib[{len(data)}] = {{",
    ]
    lines.extend("    " + ", ".join(f"0x{v:02x}" for v in data[i:i+16]) + ","
                 for i in range(0, len(data), 16))
    text = "\n".join(lines + ["};", ""])
    if args.check:
        assert OUTPUT.read_text(encoding="utf-8") == text, "Asset differs; regenerate it"
    else:
        OUTPUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"Verified {len(raw):,} RGB565 bytes -> {len(data):,} compressed bytes")


if __name__ == "__main__":
    main()
