/**
 * @file audio_port.h
 * @brief Audio output device layer: SSIE0 (I2S master) -> DA7212 -> J33 speaker
 * @details
 * Issue #46 (S-005-2). Provides:
 *   - device bring-up in the mandatory order
 *     GPT2 (MCLK) -> GPT1 (AUDIO_CLK) -> DA7212 -> R_SSI_Open()
 *   - non-blocking continuous playback built on a two-buffer (ping-pong)
 *     scheme driven by the SSI transmit interrupt / DTC
 *   - start / stop and hardware volume control
 *
 * The waveform itself is NOT generated here: the caller supplies a fill
 * callback that is invoked from the SSI ISR whenever a buffer becomes free.
 * Issue #47 (S-005-3) plugs the alarm-tone generator into that hook. A
 * minimal built-in square-wave test tone is provided for bring-up only.
 *
 * FSP instances used (all generated by Issue #45, see ra_gen/hal_data.c):
 *   g_i2s_audio        SSIE0, master, PCM 16-bit, word length 16-bit,
 *                      internal AUDIO_CLK, bit clock divider /1  (:320-332)
 *   g_transfer_i2s_tx  DTC on SSI0 TXI - opened by R_SSI_Open(), never
 *                      touched from the application            (:279-319)
 *   g_timer_audio_clk  GPT1, period 488 -> BCLK 512,295 Hz      (:131-134)
 *   g_timer_audio_mclk GPT2 -> PD06, period 20 -> MCLK 12.5 MHz (:257-260)
 *   g_comms_i2c_codec  DA7212 control, slave 0x1A               (:8-25)
 */

#ifndef AUDIO_PORT_H
#define AUDIO_PORT_H

/**********************************************************************************************************************
 Includes   <System Includes> , "Project Includes"
 *********************************************************************************************************************/
#include <stdint.h>
#include <stdbool.h>

#include <tk/tkernel.h>

#include "hal_data.h"

#ifdef __cplusplus
extern "C" {
#endif

/**********************************************************************************************************************
 Macro definitions
 *********************************************************************************************************************/

/** GPT count clock (PCLKD). PLL1P 1 GHz / 4 (ra_gen/bsp_clock_cfg.h:13,38).
 *  PCLKD (not GPTCLK) is the count source because
 *  BSP_CFG_GPT_COUNT_CLOCK_SOURCE == 1 (ra_gen/bsp_clock_cfg.h:56) makes
 *  GPT_CFG_GPTCLK_BYPASS true (ra_cfg/fsp_cfg/r_gpt_cfg.h:12-16), which
 *  selects the `#else` branch in r_gpt.c:1735-1746 at COMPILE time. */
#define AUDIO_PCLKD_HZ              (250000000UL)

/** GPT1 period in counts (ra_gen/hal_data.c:131-134, period_counts = 0x1e8) */
#define AUDIO_GPT_AUDIO_CLK_COUNTS  (488UL)

/** GPT2 period in counts (ra_gen/hal_data.c:257-260, period_counts = 0x14) */
#define AUDIO_GPT_MCLK_COUNTS       (20UL)

/**
 * SSIE bit clock divider actually used, and why it is not the generated one.
 *
 * MEASURED on hardware: with the generated SSI_CLOCK_DIV_1
 * (ra_gen/hal_data.c:323-325) the stream ran at 1669 buffers/s instead of 100,
 * i.e. the bit clock was ~16.7x too fast; with /16 it ran at 151 buf/s and
 * with /24 at exactly 100 buf/s. Back-calculating from the /16 point gives an
 * audio clock of ~12.37 MHz, which is GPT2 (AUDIO_PCLKD_HZ / 20 = 12.5 MHz),
 * NOT GPT1.
 *
 * So SSI_AUDIO_CLOCK_INTERNAL - documented only as "internal connection to a
 * MCU specific GPT channel output" (ra/fsp/inc/instances/r_ssi.h:35) - is fed
 * by GPT2 on this MCU. doc/fsp-setup-guide/issue-45-audio-output-modules.md
 * section 1-2 assumed GPT1 and that assumption is wrong: g_timer_audio_clk
 * (GPT1) counts correctly but nothing consumes its output.
 *
 * 12.5 MHz / 24 / 32 = 16276 Hz, the closest reachable rate to the 16 kHz the
 * DA7212 is programmed for (SR = 0x05) using the dividers r_ssi offers
 * (ssi_clock_div_t has no /25).
 *
 * TODO(Issue #46): this belongs in the FSP configuration - the r_ssi property
 * "Bit Clock Divider" must be changed from "Audio Clock / 1" to
 * "Audio Clock / 24". Until configuration.xml is regenerated, audio_init()
 * applies it to SSICR.CKDV directly after R_SSI_Open().
 */
#define AUDIO_SSI_BIT_CLOCK_DIV     (24UL)

/** SSICR.CKDV field value for AUDIO_SSI_BIT_CLOCK_DIV
 *  (SSI_CLOCK_DIV_24 = 10, ra/fsp/inc/instances/r_ssi.h). */
#define AUDIO_SSI_CKDV_VALUE        (10UL)

/** Bit clock = audio clock (GPT2) / AUDIO_SSI_BIT_CLOCK_DIV. */
#define AUDIO_BCLK_HZ               ((AUDIO_PCLKD_HZ / AUDIO_GPT_MCLK_COUNTS) / \
                                     AUDIO_SSI_BIT_CLOCK_DIV)

/** Master clock supplied to the DA7212 on PD06. */
#define AUDIO_MCLK_HZ               (AUDIO_PCLKD_HZ / AUDIO_GPT_MCLK_COUNTS)

/** Channels per I2S frame. I2S always carries left+right
 *  (ra/fsp/src/r_ssi/r_ssi.c:57 SSI_PRV_I2S_CHANNELS). */
#define AUDIO_CHANNELS              (2U)

/** PCM sample width in bits (ra_gen/hal_data.c:328-329, I2S_PCM_WIDTH_16_BITS) */
#define AUDIO_SAMPLE_BITS           (16U)

/** System word length in bits (ra_gen/hal_data.c:329-330,
 *  I2S_WORD_LENGTH_16_BITS) -> 32 BCLK per frame. */
#define AUDIO_WORD_BITS             (16U)

/** Actual sample rate: BCLK / (word length x channels) = 16,276 Hz against the
 *  16 kHz the DA7212 SR register selects (+1.7 %). See
 *  AUDIO_SSI_BIT_CLOCK_DIV for why /24 is the closest reachable divider. */
#define AUDIO_SAMPLE_RATE_HZ        (AUDIO_BCLK_HZ / (AUDIO_WORD_BITS * AUDIO_CHANNELS))

/** Length of ONE ping-pong buffer in milliseconds.
 *  Kept at the short end of the 10-20 ms range recommended by
 *  doc/fsp-setup-guide/issue-45-audio-output-modules.md section 10-2, so that
 *  audio_stop() reaches silence quickly. */
#define AUDIO_BUFFER_MS             (10U)

/** Frames (= L+R sample pairs) per buffer. */
#define AUDIO_BUFFER_FRAMES         ((AUDIO_SAMPLE_RATE_HZ * AUDIO_BUFFER_MS) / 1000U)

/** int16 samples per buffer (interleaved L,R,L,R...). */
#define AUDIO_BUFFER_SAMPLES        (AUDIO_BUFFER_FRAMES * AUDIO_CHANNELS)

/** Bytes per buffer. Always a multiple of 4, which R_SSI_Write() needs:
 *  it converts bytes to 16-bit samples and then to DTC blocks of 2 samples
 *  (r_ssi.c:827-838 with fifo_access_size = TRANSFER_SIZE_2_BYTE for
 *  I2S_PCM_WIDTH_16_BITS, r_ssi.c:223-226). */
#define AUDIO_BUFFER_BYTES          (AUDIO_BUFFER_SAMPLES * sizeof(int16_t))

/** Number of ping-pong buffers. */
#define AUDIO_BUFFER_COUNT          (2U)

/** Full-scale amplitude for generated test tones (about -6 dBFS). */
#define AUDIO_TEST_AMPLITUDE        (16000)

/**********************************************************************************************************************
 Global Typedef definitions
 *********************************************************************************************************************/

/** Audio output device state */
typedef enum e_audio_state
{
    AUDIO_STATE_UNINITIALIZED = 0,  /**< audio_init() not run yet */
    AUDIO_STATE_READY,              /**< initialised, not playing */
    AUDIO_STATE_PLAYING,            /**< continuous playback running */
    AUDIO_STATE_STOPPING,           /**< stop requested, waiting for I2S_EVENT_IDLE */
    AUDIO_STATE_ERROR,              /**< init or playback failed */
} audio_state_t;

/**
 * Buffer fill callback.
 *
 * @warning Called from the SSI transmit ISR (priority 2). It must be short,
 *          must not block and must not perform I2C.
 *
 * @param[out] p_frames     Interleaved L,R int16 PCM destination.
 * @param[in]  frame_count  Number of L+R frames to produce (AUDIO_BUFFER_FRAMES).
 * @param[in]  p_context    Context passed to audio_start().
 */
typedef void (*audio_fill_cb_t)(int16_t *p_frames, uint32_t frame_count, void *p_context);

/**********************************************************************************************************************
 Exported global functions
 *********************************************************************************************************************/

/**
 * Bring up the audio output device.
 *
 * Performs, in this exact order:
 *   1. R_GPT_Open/Start on GPT2  - MCLK on PD06. The codec needs a valid MCLK
 *      before any PLL register is written.
 *   2. R_GPT_Open/Start on GPT1  - SSIE internal AUDIO_CLK (= BCLK). r_ssi
 *      only sets SSICR.CKS and never opens/starts a GPT
 *      (ra/fsp/src/r_ssi/r_ssi.c:259-266), so this is the application's job.
 *   3. da7212_init()             - codec over I2C (uses the IIC1 bus lock and
 *      waits until the bus is available).
 *   4. R_SSI_Open()              - which also opens the DTC transmit instance
 *      (r_ssi.c:713-720).
 *
 * Blocks for roughly 0.4 s inside step 3. Task context only.
 *
 * @retval FSP_SUCCESS      Device ready.
 * @return                  First failing FSP error code otherwise.
 */
fsp_err_t audio_init(void);

/**
 * Start continuous playback.
 *
 * Both ping-pong buffers are filled through @p p_fill, playback is started
 * and the codec is unmuted. Returns immediately; the ISR keeps the stream
 * running by calling @p p_fill for each buffer that becomes free.
 *
 * @param[in] p_fill        Buffer producer. NULL selects the built-in test
 *                          tone configured with audio_set_test_tone().
 * @param[in] p_context     Passed back to @p p_fill.
 *
 * @retval FSP_SUCCESS      Playback started.
 * @retval FSP_ERR_NOT_OPEN audio_init() has not succeeded.
 * @retval FSP_ERR_IN_USE   Already playing.
 */
fsp_err_t audio_start(audio_fill_cb_t p_fill, void *p_context);

/**
 * Stop playback.
 *
 * Mutes the codec first (immediate silence), then requests the SSI to stop
 * and waits for the I2S_EVENT_IDLE callback.
 *
 * @retval FSP_SUCCESS      Stopped.
 * @retval FSP_ERR_TIMEOUT  I2S_EVENT_IDLE did not arrive; the SSI was forced
 *                          to stop anyway.
 */
fsp_err_t audio_stop(void);

/**
 * Set the hardware (DA7212 LINE amplifier) volume.
 *
 * @param[in] percent   0 = mute .. 100 = maximum. Values > 100 are clamped.
 */
fsp_err_t audio_set_volume(uint8_t percent);

/** @return the current volume percentage. */
uint8_t audio_get_volume(void);

/** Configure the built-in test tone used when audio_start(NULL, NULL) is called. */
fsp_err_t audio_set_test_tone(uint32_t freq_hz, uint16_t amplitude);

/** @return current device state. */
audio_state_t audio_get_state(void);

/** @return the actual sample rate in Hz. */
uint32_t audio_get_sample_rate(void);

/**
 * uT-Kernel task entry: runs audio_init() once, then sleeps forever.
 * Created and started from usermain().
 */
void audio_task(INT stacd, void *exinf);

/** NT-Shell "audio" command handler. */
int usrcmd_audio(int argc, char **argv);

#ifdef __cplusplus
}
#endif

#endif /* AUDIO_PORT_H */
