/**
 * @file lv_port_indev.c
 * @brief Touch panel input device port layer implementation
 * @details
 * Implements the GT911/FT5X06-compatible touch panel driver for LVGL on the
 * EK-RA8P1 Parallel Graphics Expansion Board. Reads touch coordinates via I2C
 * and reports them to LVGL as pointer input events.
 *
 * This module provides:
 *   - Touch panel initialization (I2C open, IRQ enable, LVGL indev create)
 *   - Periodic touch data reading via LVGL indev callback
 *   - Touch IRQ callback for event-driven notification
 *   - I2C communication callback for async transfer completion
 *   - NT-Shell "touch" command for diagnostics
 *
 * I2C Communication Flow (R-006: uT-Kernel 3.0):
 *   1. touchpad_read() callback is called by LVGL periodically
 *   2. Checks the touch IRQ semaphore (s_touch_irq_semid) to detect new touch events
 *   3. If touch detected, sends I2C write-read to register 0x02 (TD_STATUS)
 *   4. RM_COMMS_I2C_WriteRead() sends register address, then reads payload
 *      (callback mode: bus blocking semaphore / recursive mutex NULL-ed)
 *   5. comms_i2c_callback() sets the event flag (s_touch_i2c_flgid) on completion
 *   6. i2c_wait() blocks on the event flag until completion or timeout
 *   7. Touch data is parsed and reported to LVGL
 *
 * Reference:
 *   - reference_projects/lv_port_renesas_ek_ra8p1/src/port/lv_port_indev.c (entire file)
 *   - reference_projects/lv_port_renesas_ek_ra8p1/src/port/lv_port_indev.h
 *   - reference_projects/lv_port_renesas_ek_ra8p1/ra_gen/new_thread0.h:14-24
 *   - reference_projects/lv_port_renesas_ek_ra8p1/ra_gen/new_thread0.c:17-36
 *
 * @note
 * This file is part of the touch panel control (F-001-5) implementation.
 *
 * @note
 * IMPORTANT: This module requires FSP configuration for I2C and External IRQ
 * (Issue #3). Until the FSP modules are added to configuration.xml, this file
 * will not compile. The required FSP instances are documented in
 * lv_port_indev.h and in the "FSP Configuration Required" section below.
 */

/**********************************************************************************************************************
 Includes   <System Includes> , "Project Includes"
 *********************************************************************************************************************/
#include <stdio.h>
#include <string.h>
#include <assert.h>

#include "lv_port_indev.h"
#include "hal_data.h"
#include "jlink_console.h"
#include "cmd_utils.h"
#include "ntlibc.h"

/* R-006 (Issue #156): FreeRTOS headers removed. RTOS dependencies were
 * replaced with uT-Kernel 3.0:
 *   g_i2c_event_group (xEventGroup*)      -> s_touch_i2c_flgid (tk_*_flg)
 *   g_irq_binary_semaphore (xSemaphore*)  -> s_touch_irq_semid (tk_*_sem)
 *   vTaskDelay                            -> tk_dly_tsk (ms)
 * Both ra_gen objects (created by g_hal_init/g_common_init) are NEVER
 * created under boot method A, so src-side uT-Kernel objects are created
 * here instead (same pattern as ov5640.c in R-005).
 * Additionally the rm_comms_i2c bus is switched to CALLBACK MODE by
 * NULL-ing its blocking semaphore / recursive mutex pointers at runtime
 * (see lv_port_indev_init Step 3). */
#include <tk/tkernel.h>

/* Issue #46: the IIC1 shared-bus open responsibility and the bus mutex now
 * live in this module (see lv_port_indev_init Step 2 and touchpad_get_xy).
 * The camera_thread_i2c_done() handshake that used to be performed directly
 * here moved into i2c_bus0_open_once(), which is why camera_thread_api.h is
 * no longer included by this file. */
#include "i2c_bus0.h"

/*
 * FSP-generated headers for I2C and External IRQ
 *
 * These headers are generated by FSP when the I2C Communication Device
 * (rm_comms_i2c) and External IRQ (r_icu) modules are added to the
 * lvgl_thread in configuration.xml.
 *
 * Until Issue #3 (FSP configuration for I2C/IRQ) is completed,
 * these includes will cause compilation errors. This is intentional -
 * the touch panel driver cannot function without the underlying
 * I2C and IRQ hardware drivers.
 *
 * Required FSP modules (to be added to lvgl_thread):
 *   - I2C Communication Device (rm_comms_i2c): g_comms_i2c_device0
 *   - I2C Shared Bus (rm_comms_i2c): g_comms_i2c_bus0
 *   - I2C Master (r_iic_master): IIC1
 *   - External IRQ (r_icu): g_external_irq0, channel 19
 *   - FreeRTOS Event Group: g_i2c_event_group
 *   - FreeRTOS Binary Semaphore: g_irq_binary_semaphore
 *
 * Reference: reference_projects/lv_port_renesas_ek_ra8p1/ra_gen/new_thread0.h:14-15
 */
#include "rm_comms_i2c.h"
#include "rm_comms_api.h"

/**********************************************************************************************************************
 Macro definitions
 *********************************************************************************************************************/

/** Console output buffer size */
#define TOUCH_PRINT_BUF_SIZE    (128)

/**
 * Maximum number of simultaneous touch points supported by FT5X06/GT911
 *
 * Reference: reference_projects/lv_port_renesas_ek_ra8p1/src/port/lv_port_indev.c:7
 */
#define FT5X06_NUM_POINTS       (5)

/**
 * FT5X06 touch event types
 *
 * Reference: reference_projects/lv_port_renesas_ek_ra8p1/src/port/lv_port_indev.c:9-12
 */
#define FT5X06_DOWN             (0)
#define FT5X06_UP               (1)
#define FT5X06_CONTACT          (2)
#define FT5X06_NO_EVENT         (3)

/**
 * FT5X06 register addresses
 *
 * TD_STATUS (0x02): Contains the number of active touch points in bits [3:0].
 * Followed by 5 sets of touch point data (6 bytes each).
 *
 * Reference: reference_projects/lv_port_renesas_ek_ra8p1/src/port/lv_port_indev.c:14
 */
#define FT5X06_REG_TD_STATUS    (0x02)

/**
 * I2C transfer event bits for the uT-Kernel event flag (s_touch_i2c_flgid).
 * Bit patterns are reused as-is from the former FreeRTOS event group.
 *
 * Reference: reference_projects/lv_port_renesas_ek_ra8p1/src/port/lv_port_indev.c:17-18
 */
#define I2C_TRANSFER_COMPLETE   (1 << 0)
#define I2C_TRANSFER_ABORT      (1 << 1)

/**
 * I2C transfer timeout in milliseconds (uT-Kernel TMO is ms-based).
 * R-006: portTICK_PERIOD_MS dependency removed (was 1000 ticks @ 1ms tick).
 */
#define I2C_TIMEOUT_MS          (1000)

/**
 * External IRQ channel number for touch panel INT pin
 *
 * The GT911 touch controller INT pin is connected to IRQ19 on the
 * EK-RA8P1 Parallel Graphics Expansion Board.
 *
 * Reference: reference_projects/lv_port_renesas_ek_ra8p1/src/port/lv_port_indev.c:157
 * Reference: reference_projects/lv_port_renesas_ek_ra8p1/configuration.xml:532
 */
#define TOUCH_IRQ_CHANNEL       (19)

/**********************************************************************************************************************
 Global Typedef definitions
 *********************************************************************************************************************/

/**
 * FT5X06/GT911 raw touch point data structure (6 bytes per point)
 *
 * Bit field layout:
 *   Byte 0: [7:6] event (DOWN/UP/CONTACT/NO_EVENT), [5:4] reserved, [3:0] x_msb
 *   Byte 1: [7:0] x_lsb
 *   Byte 2: [7:4] id (touch point ID), [3:0] y_msb
 *   Byte 3: [7:0] y_lsb
 *   Byte 4: reserved
 *   Byte 5: reserved
 *
 * Reference: reference_projects/lv_port_renesas_ek_ra8p1/src/port/lv_port_indev.c:22-35
 */
typedef struct st_ft5x06_touch
{
    uint8_t  x_msb : 4;
    uint8_t        : 2;
    uint8_t  event : 2;
    uint8_t  x_lsb;

    uint8_t  y_msb : 4;
    uint8_t  id    : 4;
    uint8_t  y_lsb : 8;

    uint8_t  res1;
    uint8_t  res2;
} ft5x06_touch_t;

/**
 * Complete FT5X06 data payload (number of active points + all five touch points)
 *
 * Reference: reference_projects/lv_port_renesas_ek_ra8p1/src/port/lv_port_indev.c:38-42
 */
typedef struct st_ft5x06_payload
{
    uint8_t        num_points_active;
    ft5x06_touch_t data_raw[FT5X06_NUM_POINTS];
} ft5x06_payload_t;

/**
 * Parsed touch coordinate with LVGL event state
 *
 * Reference: reference_projects/lv_port_renesas_ek_ra8p1/src/port/lv_port_indev.c:45-50
 */
typedef struct st_touch_coord
{
    uint16_t         x;
    uint16_t         y;
    lv_indev_state_t event;
} touch_coord_t;

/**
 * Parsed touch data for all points
 *
 * Reference: reference_projects/lv_port_renesas_ek_ra8p1/src/port/lv_port_indev.c:52-56
 */
typedef struct st_touch_data
{
    uint8_t       num_points;
    touch_coord_t point[FT5X06_NUM_POINTS];
} touch_data_t;

/**
 * Touch panel initialization status
 */
typedef enum {
    TOUCH_STATUS_NOT_INITIALIZED = 0,   /**< Not yet initialized */
    TOUCH_STATUS_INITIALIZED,           /**< Successfully initialized */
    TOUCH_STATUS_ERROR,                 /**< Initialization failed */
} touch_status_t;

/**********************************************************************************************************************
 Macro functions
 *********************************************************************************************************************/

/**
 * Extract event, x-coordinate, and y-coordinate from raw touch data
 *
 * Reference: reference_projects/lv_port_renesas_ek_ra8p1/src/port/lv_port_indev.c:58-60
 */
#define extract_e(t)    ((uint8_t)  ((t).event))
#define extract_x(t)    ((int16_t)  (((t).x_msb << 8) | ((t).x_lsb)))
#define extract_y(t)    ((int16_t)  (((t).y_msb << 8) | ((t).y_lsb)))

/**********************************************************************************************************************
 Private (static) functions prototypes
 *********************************************************************************************************************/

/**
 * LVGL touchpad read callback
 *
 * Called by LVGL periodically to poll for touch input.
 * In polling mode, checks the IRQ semaphore first.
 * In event-driven mode, reads touch data directly.
 *
 * Reference: reference_projects/lv_port_renesas_ek_ra8p1/src/port/lv_port_indev.c:246-273
 */
static void touchpad_read(lv_indev_t *indev, lv_indev_data_t *data);

/**
 * Wait for I2C transfer completion using FreeRTOS EventGroup
 *
 * Reference: reference_projects/lv_port_renesas_ek_ra8p1/src/port/lv_port_indev.c:199-225
 */
static fsp_err_t i2c_wait(void);

/**
 * Check if a touch event is pending (polling mode)
 *
 * Reference: reference_projects/lv_port_renesas_ek_ra8p1/src/port/lv_port_indev.c:227-239
 */
static bool touchpad_is_pressed(void);

/**
 * Read touch coordinates from the FT5X06/GT911 controller via I2C
 *
 * Reference: reference_projects/lv_port_renesas_ek_ra8p1/src/port/lv_port_indev.c:275-338
 */
static void touchpad_get_xy(lv_indev_data_t *data);

/* NT-Shell sub-command handlers */
static void touch_cmd_status(void);
static void touch_cmd_info(void);
static void touch_cmd_read(void);
static void touch_cmd_mon(int argc, char **argv);

/**********************************************************************************************************************
 Private (static) variables
 *********************************************************************************************************************/

/** LVGL input device handle */
static lv_indev_t *s_indev_touchpad = NULL;

/**
 * Global touch data (latest parsed result)
 *
 * Reference: reference_projects/lv_port_renesas_ek_ra8p1/src/port/lv_port_indev.c:62
 */
static touch_data_t s_touch_data;

/** Touch panel initialization status */
static touch_status_t s_touch_status = TOUCH_STATUS_NOT_INITIALIZED;

/** Touch event counter (incremented on each touch read) */
static volatile uint32_t s_touch_read_count = 0;

/** Issue #46 diagnostics: i2c_bus0_lock() failures in touchpad_get_xy(). */
static volatile uint32_t  s_touch_lock_fail_count = 0;
static volatile fsp_err_t s_touch_last_lock_err   = FSP_SUCCESS;

/** Issue #46 diagnostics: I2C transfer failures that used to be assert(). */
static volatile uint32_t  s_touch_xfer_fail_count = 0;
static volatile fsp_err_t s_touch_last_xfer_err   = FSP_SUCCESS;

/**
 * Issue #46 diagnostics: raw bytes of the most recent FT5X06 register read.
 *
 * "Read count climbs but every point is RELEASED" has two very different
 * causes and the parsed result cannot tell them apart: either the controller
 * really reports no contact, or the transfer went to the WRONG SLAVE. The
 * codec (0x1A) now shares this bus and rm_comms_i2c rewrites the slave address
 * per device (rm_comms_i2c_driver_ra.c rm_comms_i2c_bus_reconfigure), so a
 * missed switch would read DA7212 registers instead of the panel's - and
 * DA7212 0x02 (STATUS1) is all-reserved, which parses as zero touch points.
 * All-zero raw bytes therefore point at the address, not at the panel.
 */
static uint8_t s_touch_raw[sizeof(ft5x06_payload_t)];
static bool    s_touch_raw_valid = false;

/** Last touch x/y for diagnostics */
static volatile int16_t s_last_touch_x = -1;
static volatile int16_t s_last_touch_y = -1;

/** Last touch state for diagnostics */
static volatile lv_indev_state_t s_last_touch_state = LV_INDEV_STATE_RELEASED;

/**
 * uT-Kernel event flag ID for I2C transfer completion (R-006).
 *
 * Replaces the FreeRTOS g_i2c_event_group (ra_gen/common_data.c), which is
 * created by g_common_init() - never executed under boot method A.
 * Set by comms_i2c_callback() (ISR, tk_set_flg) and waited on by i2c_wait()
 * (task, tk_wai_flg). 0 = not yet created.
 */
static ID s_touch_i2c_flgid = 0;

/**
 * uT-Kernel semaphore ID for touch IRQ notification (R-006).
 *
 * Replaces the FreeRTOS g_irq_binary_semaphore (ra_gen/common_data.c).
 * Binary equivalent: counting semaphore with maxsem=1 (tk_sig_sem saturates
 * with E_QOVR, which is ignored - same as a binary semaphore Give).
 * Signaled by touch_irq_callback() (ISR) and polled by touchpad_is_pressed()
 * (TMO_POL). 0 = not yet created.
 */
static ID s_touch_irq_semid = 0;

/**********************************************************************************************************************
 Private (static) functions  - uT-Kernel sync object creation (R-006)
 *********************************************************************************************************************/

/**
 * Create the uT-Kernel synchronization objects for the touch panel driver.
 *
 * Idempotent (re-creation is skipped). Must be called before the I2C device
 * and the external IRQ are opened, because the FSP callbacks (ISR context)
 * reference these IDs. Same pattern as ov5640_i2c_sync_init() (R-005).
 *
 * @retval true   both objects are available
 * @retval false  creation failed (touch panel stays non-functional)
 */
static bool touch_sync_init(void)
{
    if (s_touch_i2c_flgid <= 0)
    {
        T_CFLG cflg = {
            .exinf   = NULL,
            .flgatr  = TA_TFIFO | TA_WMUL,
            .iflgptn = 0,
        };
        ID flgid = tk_cre_flg(&cflg);
        if (flgid <= E_OK)
        {
            print_to_console("lv_port_indev: tk_cre_flg failed\r\n");
            return false;
        }
        s_touch_i2c_flgid = flgid;
    }

    if (s_touch_irq_semid <= 0)
    {
        T_CSEM csem = {
            .exinf   = NULL,
            .sematr  = TA_TFIFO | TA_FIRST,
            .isemcnt = 0,
            .maxsem  = 1,
        };
        ID semid = tk_cre_sem(&csem);
        if (semid <= E_OK)
        {
            print_to_console("lv_port_indev: tk_cre_sem failed\r\n");
            return false;
        }
        s_touch_irq_semid = semid;
    }

    return true;
}

/**********************************************************************************************************************
 Exported global functions (callbacks called from FSP-generated code)
 *********************************************************************************************************************/

/**
 * Touch panel external IRQ callback
 *
 * @details Called from the ICU external interrupt handler when the GT911
 *          touch controller asserts the INT pin (falling edge on IRQ19).
 *          Gives the IRQ binary semaphore to notify the LVGL thread that
 *          new touch data is available.
 *
 *          This function name must match the callback configured in FSP:
 *            External IRQ -> g_external_irq0 -> Callback: touch_irq_callback
 *
 * @note This function runs in ISR context. tk_sig_sem is a notification
 *       call and may be issued from an interrupt handler (migration guide
 *       5.1). uT-Kernel performs delayed dispatch at interrupt exit, so the
 *       FreeRTOS portYIELD_FROM_ISR equivalent is not needed.
 *
 * R-006: xSemaphoreGiveFromISR(g_irq_binary_semaphore) -> tk_sig_sem.
 *        E_QOVR (semaphore already full, maxsem=1) is ignored - same
 *        saturation behavior as the former binary semaphore.
 *
 * Reference: reference_projects/lv_port_renesas_ek_ra8p1/src/port/lv_port_indev.c:155-167
 *
 * @param p_args  External IRQ callback arguments (contains channel number)
 */
void touch_irq_callback(external_irq_callback_args_t *p_args)
{
    if (TOUCH_IRQ_CHANNEL == p_args->channel)
    {
        /*
         * Signal the IRQ semaphore to notify touchpad_is_pressed()
         * that new touch data is available for reading.
         */
        (void)tk_sig_sem(s_touch_irq_semid, 1);
    }
}

/**
 * I2C communication callback
 *
 * @details Called from the RM_COMMS_I2C driver when an I2C transfer
 *          completes (successfully or with error). Sets the appropriate
 *          bit in the uT-Kernel event flag to unblock i2c_wait().
 *
 *          This function name must match the callback configured in FSP:
 *            I2C Communication Device -> g_comms_i2c_device0 -> Callback: comms_i2c_callback
 *
 *          With the bus switched to callback mode (blocking semaphore /
 *          recursive mutex NULL-ed in lv_port_indev_init Step 3), the
 *          rm_comms_i2c driver invokes this callback without touching any
 *          FreeRTOS object (rm_comms_i2c_driver_ra.c:321-338).
 *
 * @note This function runs in ISR context. tk_set_flg is a notification
 *       call and may be issued from an interrupt handler (migration guide
 *       5.1); no explicit yield is needed (delayed dispatch).
 *
 * R-006: xEventGroupSetBitsFromISR(g_i2c_event_group) -> tk_set_flg
 *        (same pattern as i2c_camera_callback in ov5640.c, R-005).
 *
 * Reference: reference_projects/lv_port_renesas_ek_ra8p1/src/port/lv_port_indev.c:169-197
 *
 * @param p_args  I2C callback arguments (contains event type)
 */
void comms_i2c_callback(rm_comms_callback_args_t *p_args)
{
    if (RM_COMMS_EVENT_OPERATION_COMPLETE == p_args->event)
    {
        (void)tk_set_flg(s_touch_i2c_flgid, I2C_TRANSFER_COMPLETE);
    }
    else if (RM_COMMS_EVENT_ERROR == p_args->event)
    {
        (void)tk_set_flg(s_touch_i2c_flgid, I2C_TRANSFER_ABORT);
    }
    else
    {
        /* Should never get here */
    }
}

/**********************************************************************************************************************
 Exported global functions
 *********************************************************************************************************************/

/**
 * Initialize the touch panel input device
 *
 * Reference: reference_projects/lv_port_renesas_ek_ra8p1/src/port/lv_port_indev.c:95-149
 */
void lv_port_indev_init(void)
{
    fsp_err_t err;

    /*
     * Step 0 (R-006): Create the uT-Kernel synchronization objects
     * (I2C completion event flag / touch IRQ semaphore) BEFORE any FSP
     * open call registers the ISR callbacks that signal them.
     */
    if (!touch_sync_init())
    {
        s_touch_status = TOUCH_STATUS_ERROR;
        return;
    }

    /*
     * Step 1: Create and register LVGL input device
     *
     * Create a pointer-type input device and register the touchpad_read
     * callback. LVGL will call this callback periodically to check for
     * new touch events.
     *
     * Reference: reference_projects/lv_port_renesas_ek_ra8p1/src/port/lv_port_indev.c:104-106
     */
    s_indev_touchpad = lv_indev_create();
    lv_indev_set_type(s_indev_touchpad, LV_INDEV_TYPE_POINTER);
    lv_indev_set_read_cb(s_indev_touchpad, touchpad_read);

#if (1 == INDEV_EVENT_DRIVEN)
    /* Update the input device's running mode to LV_INDEV_MODE_EVENT */
    lv_indev_set_mode(s_indev_touchpad, LV_INDEV_MODE_EVENT);
#endif

    /*
     * Step 2 / 2b / 3: Acquire the IIC1 shared bus.
     *
     * Issue #46: the three steps that used to live here (wait for the camera
     * to release IIC1 -> open g_i2c_master0 -> NULL the rm_comms_i2c
     * semaphore/mutex pointers to select callback mode) moved verbatim into
     * i2c_bus0_open_once() (src/port/i2c_bus0.c), because the touch panel is
     * no longer the only user of this bus: the DA7212 audio CODEC
     * (g_comms_i2c_codec, slave 0x1A) sits on the same shared bus
     * (ra_gen/hal_data.c:14). The order and the semantics are unchanged:
     *
     *   - camera_thread_i2c_done() is still waited on BEFORE the open, which
     *     is what prevents the Issue #93 IIC1 IRQ-context conflict
     *     (r_iic_master.c:784-787).
     *   - the `#if BSP_CFG_RTOS` guarded NULL assignments are still performed
     *     BEFORE RM_COMMS_I2C_Open() below.
     *   - the open happens exactly once even if the audio task gets there
     *     first.
     *
     * What is NEW is that every touch transfer must now be wrapped in
     * i2c_bus0_lock()/i2c_bus0_unlock() (see touchpad_get_xy), because
     * rm_comms_i2c rewrites the shared slave address and lower level callback
     * on every device switch (rm_comms_i2c_driver_ra.c:345-380) and the
     * middleware's own bus mutex does not exist in this build
     * (rm_comms_i2c.h:90-93 with BSP_CFG_RTOS == 0).
     */
    /*
     * Not an assert: assert() reaches newlib's abort() in this build (NDEBUG
     * is not defined) and would hang lvgl_task forever, taking the whole UI
     * with it, while the shell keeps answering. Losing the touch panel is bad;
     * losing the display too is worse. Leave s_touch_status at
     * NOT_INITIALIZED so `touch status` reports it and the LVGL side still
     * comes up.
     */
    /*
     * One call, one lock: the shared master and this device are opened
     * together. Splitting them would let a camera diagnostic close the master
     * in between and make RM_COMMS_I2C_Open() fail with
     * FSP_ERR_COMMS_BUS_NOT_OPEN (see i2c_bus0_open_device).
     *
     * Not an assert: assert() reaches newlib's abort() in this build (NDEBUG
     * is not defined) and would hang lvgl_task forever, taking the whole UI
     * with it, while the shell keeps answering. Losing the touch panel is bad;
     * losing the display too is worse. Leave s_touch_status at
     * NOT_INITIALIZED so `touch status` reports it and LVGL still comes up.
     */
    err = i2c_bus0_open_device(&g_comms_i2c_device0_ctrl, &g_comms_i2c_device0_cfg);
    if (FSP_SUCCESS != err)
    {
        char err_buf[TOUCH_PRINT_BUF_SIZE];
        snprintf(err_buf, sizeof(err_buf),
                 "lv_port_indev: IIC1 shared bus/device open failed (err=0x%lX); touch disabled.\r\n",
                 (unsigned long)err);
        print_to_console(err_buf);
        return;
    }

    /*
     * Step 4: the I2C communication device is already open.
     *
     * RM_COMMS_I2C_Open() - which configures the slave address (0x38 for
     * GT911/FT5X06) and the communication parameters - was performed by
     * i2c_bus0_open_device() above, under the same lock as the master open.
     *
     * Note: The LCD reset (performed in glcdc_port_init) is shared with
     * the touch controller. The touch controller must be initialized
     * after the LCD reset sequence.
     *
     * Reference: reference_projects/lv_port_renesas_ek_ra8p1/src/port/lv_port_indev.c:141-142
     */

    /*
     * Step 5: Open and enable external IRQ for touch events
     *
     * The GT911 INT pin generates a falling-edge interrupt when new
     * touch data is available. The IRQ callback (touch_irq_callback)
     * signals s_touch_irq_semid (tk_sig_sem) to notify the LVGL task.
     *
     * Reference: reference_projects/lv_port_renesas_ek_ra8p1/src/port/lv_port_indev.c:144-148
     */
    /* Same reasoning as the bus open above: an assert() here would abort()
     * and hang lvgl_task, killing the display along with the touch panel. */
    err = R_ICU_ExternalIrqOpen(&g_external_irq0_ctrl, &g_external_irq0_cfg);
    if (FSP_SUCCESS == err)
    {
        err = R_ICU_ExternalIrqEnable(&g_external_irq0_ctrl);
    }

    if (FSP_SUCCESS != err)
    {
        char err_buf[TOUCH_PRINT_BUF_SIZE];
        snprintf(err_buf, sizeof(err_buf),
                 "lv_port_indev: touch IRQ setup failed (err=0x%lX); touch disabled.\r\n",
                 (unsigned long)err);
        print_to_console(err_buf);
        return;
    }

    s_touch_status = TOUCH_STATUS_INITIALIZED;
}

/**
 * Get the LVGL input device handle
 */
lv_indev_t *lv_port_indev_get(void)
{
    return s_indev_touchpad;
}

/**********************************************************************************************************************
 Private (static) functions
 *********************************************************************************************************************/

/**
 * Wait for I2C transfer completion
 *
 * @details Blocks on the uT-Kernel event flag until either the transfer
 *          completes successfully, aborts with error, or times out.
 *
 * R-006: xEventGroupWaitBits -> tk_wai_flg(TWF_ORW | TWF_BITCLR, ms timeout)
 *        (same pattern as ov5640_i2c_wait_complete in ov5640.c, R-005).
 *        TWF_ORW  = wait for ANY of the bits ("either bit will do")
 *        TWF_BITCLR = clear the satisfied bits on return
 *
 * Reference: reference_projects/lv_port_renesas_ek_ra8p1/src/port/lv_port_indev.c:199-225
 *
 * @retval FSP_SUCCESS       Transfer completed successfully
 * @retval FSP_ERR_ABORTED   Transfer aborted due to I2C error
 * @retval FSP_ERR_TIMEOUT   Transfer timed out (or flag wait failed)
 */
static fsp_err_t i2c_wait(void)
{
    fsp_err_t ret = FSP_SUCCESS;
    UINT flgptn = 0;

    ER ercd = tk_wai_flg(s_touch_i2c_flgid,
                         (UINT)(I2C_TRANSFER_COMPLETE | I2C_TRANSFER_ABORT),
                         TWF_ORW | TWF_BITCLR,
                         &flgptn,
                         (TMO)I2C_TIMEOUT_MS);

    if (E_OK != ercd)
    {
        /* E_TMOUT or other flag error: report as timeout.
         *
         * Issue #46: abort the transfer before the caller releases the bus
         * lock and clear the event flag - a timeout does not stop the lower
         * level transfer, and a late callback would otherwise satisfy the next
         * wait as a false completion (see i2c_bus0_abort_transfer). */
        (void)i2c_bus0_abort_transfer();
        (void)tk_clr_flg(s_touch_i2c_flgid, 0);

        ret = FSP_ERR_TIMEOUT;
    }
    else if ((I2C_TRANSFER_COMPLETE & flgptn) == I2C_TRANSFER_COMPLETE)
    {
        ret = FSP_SUCCESS;
    }
    else
    {
        /* I2C_TRANSFER_ABORT was set */
        ret = FSP_ERR_ABORTED;
    }

    return ret;
}

/**
 * Check if a touch event is pending
 *
 * @details Attempts to take the IRQ semaphore without waiting (TMO_POL).
 *          Returns true if the semaphore was available, indicating that
 *          touch_irq_callback() was called since the last check.
 *
 * R-006: xSemaphoreTake(g_irq_binary_semaphore, 0)
 *        -> tk_wai_sem(s_touch_irq_semid, 1, TMO_POL).
 *
 * Reference: reference_projects/lv_port_renesas_ek_ra8p1/src/port/lv_port_indev.c:227-239
 *
 * @retval true   Touch event is pending (semaphore was taken)
 * @retval false  No touch event pending
 */
static bool touchpad_is_pressed(void)
{
    return (E_OK == tk_wai_sem(s_touch_irq_semid, 1, TMO_POL));
}

/**
 * LVGL touchpad read callback
 *
 * @details Called by LVGL periodically to poll for touch input.
 *
 * In polling mode (INDEV_EVENT_DRIVEN == 0):
 *   - First checks if a touch event is pending via touchpad_is_pressed()
 *   - If pending, reads touch data via I2C
 *   - If not pending, returns the last known state and coordinates
 *   - This minimizes I2C bus traffic by only reading when touch IRQ fires
 *
 * In event-driven mode (INDEV_EVENT_DRIVEN == 1):
 *   - Reads touch data directly on every LVGL poll
 *
 * Reference: reference_projects/lv_port_renesas_ek_ra8p1/src/port/lv_port_indev.c:246-273
 *
 * @param indev  LVGL input device handle (unused)
 * @param data   Output: touch state and coordinates
 */
static void touchpad_read(lv_indev_t *indev, lv_indev_data_t *data)
{
    FSP_PARAMETER_NOT_USED(indev);

    data->state = LV_INDEV_STATE_RELEASED;

#if (1 == INDEV_EVENT_DRIVEN)
    touchpad_get_xy(data);
#else
    /*
     * Polling mode: Save the pressed coordinates and the state.
     * Only perform I2C read when the IRQ semaphore indicates new data.
     *
     * Reference: reference_projects/lv_port_renesas_ek_ra8p1/src/port/lv_port_indev.c:256-271
     */
    static lv_indev_state_t last_state = LV_INDEV_STATE_RELEASED;
    static lv_point_t last_point = {.x = 0, .y = 0};

    if (touchpad_is_pressed()) {
        touchpad_get_xy(data);
        last_state = data->state;
        last_point.x = data->point.x;
        last_point.y = data->point.y;
    }
    else
    {
        data->state   = last_state;
        data->point.x = last_point.x;
        data->point.y = last_point.y;
    }
#endif
}

/**
 * Read touch coordinates from the FT5X06/GT911 controller
 *
 * @details Performs an I2C write-read transaction to read the touch status
 *          register (0x02) and all five touch point data sets. Parses the
 *          raw bit-field data into x/y coordinates and event types.
 *
 *          I2C transaction:
 *            Write: 1 byte (register address 0x02)
 *            Read:  31 bytes (1 byte status + 5 x 6 bytes touch data)
 *
 *          Only the first touch point is reported to LVGL (single-touch).
 *          Multi-touch data is parsed but not used by LVGL's pointer model.
 *
 * Reference: reference_projects/lv_port_renesas_ek_ra8p1/src/port/lv_port_indev.c:275-338
 *
 * @param data  Output: touch state and coordinates for LVGL
 */
static void touchpad_get_xy(lv_indev_data_t *data)
{
    fsp_err_t err;
    rm_comms_write_read_params_t write_read_params;
    ft5x06_payload_t touch_payload;
    uint8_t event;
    uint8_t reg;
    uint8_t touch_count;

    reg = FT5X06_REG_TD_STATUS;

    write_read_params.src_bytes  = 1;
    write_read_params.p_src      = &reg;
    write_read_params.p_dest     = (uint8_t *)&touch_payload;
    write_read_params.dest_bytes = sizeof(ft5x06_payload_t);

    /*
     * Write TD_STATUS address, then read status + all five touch point registers.
     *
     * Issue #46: the submit AND the completion wait are inside the IIC1 bus
     * lock. Both are required to be atomic with respect to the other bus user
     * (DA7212): rm_comms_i2c_bus_reconfigure() rewrites the shared
     * p_current_ctrl / slave address / lower level callback whenever the
     * requesting device differs from the previous one
     * (ra/fsp/src/rm_comms_i2c/rm_comms_i2c_driver_ra.c:345-380), so a
     * concurrent codec transfer between the submit and the completion would
     * redirect this transfer's callback.
     *
     * Reference: reference_projects/lv_port_renesas_ek_ra8p1/src/port/lv_port_indev.c:293-294
     */
    err = i2c_bus0_lock();
    if (FSP_SUCCESS != err)
    {
        /* Bus busy/unavailable (>= I2C_BUS0_LOCK_TIMEOUT_MS): report
         * "released" for this cycle rather than corrupting a transfer that
         * belongs to another device on the bus.
         *
         * Issue #46: this is the ONLY path out of touchpad_get_xy() that
         * reports RELEASED without having talked to the controller, and it
         * leaves s_touch_read_count untouched. Counting it separately is what
         * distinguishes "the bus lock failed" from "the panel reported no
         * touch" in touch status - the two look identical from the outside. */
        s_touch_lock_fail_count++;
        s_touch_last_lock_err = err;
        data->state = LV_INDEV_STATE_RELEASED;
        return;
    }

    /*
     * Issue #46: these two failures used to be assert(). NDEBUG is not defined
     * in this build, so assert() reaches newlib's abort() and hangs WHATEVER
     * TASK is running - here that is lvgl_task, i.e. one transient I2C hiccup
     * freezes the whole UI while the shell keeps answering, which is a very
     * confusing failure mode to debug.
     *
     * That risk is higher now than before this Issue: the DA7212 is a second
     * user of this bus, so a touch transfer can now fail for reasons outside
     * the touch driver. A dropped sample is not worth killing the UI for -
     * count it, report "released" for this cycle and let the next poll retry.
     */
    err = RM_COMMS_I2C_WriteRead(&g_comms_i2c_device0_ctrl, write_read_params);
    if (FSP_SUCCESS != err)
    {
        (void)i2c_bus0_unlock();
        s_touch_xfer_fail_count++;
        s_touch_last_xfer_err = err;
        data->state = LV_INDEV_STATE_RELEASED;
        return;
    }

    err = i2c_wait();

    (void)i2c_bus0_unlock();

    if (FSP_SUCCESS != err)
    {
        s_touch_xfer_fail_count++;
        s_touch_last_xfer_err = err;
        data->state = LV_INDEV_STATE_RELEASED;
        return;
    }

    /* Snapshot the raw bytes before any parsing (see s_touch_raw). */
    memcpy(s_touch_raw, &touch_payload, sizeof(s_touch_raw));
    s_touch_raw_valid = true;

    /* Extract active touch count from lower nibble */
    touch_count = touch_payload.num_points_active & 0x0F;

    if (FT5X06_NUM_POINTS < touch_count)
    {
        /* Garbage count (bus glitch, or the answer came from another slave).
         *
         * Drop the whole sample - do NOT clamp and parse. If the count is
         * corrupt the point records behind it are corrupt too, so parsing them
         * would hand LVGL a PRESSED event at an arbitrary coordinate and turn
         * a detected corruption into a phantom tap. The next poll retries. */
        s_touch_xfer_fail_count++;
        data->state = LV_INDEV_STATE_RELEASED;
        return;
    }

    /* Reset all points to released before parsing new data */
    for (uint8_t i = 0; i < FT5X06_NUM_POINTS; i++)
    {
        s_touch_data.point[i].event = LV_INDEV_STATE_RELEASED;
    }

    /*
     * Process the raw data for the touch point(s) into useful coordinates.
     *
     * Reference: reference_projects/lv_port_renesas_ek_ra8p1/src/port/lv_port_indev.c:310-329
     */
    for (uint8_t i = 0; i < touch_count; i++)
    {
        s_touch_data.point[i].x = (uint16_t)extract_x(touch_payload.data_raw[i]);
        s_touch_data.point[i].y = (uint16_t)extract_y(touch_payload.data_raw[i]);
        event                   = extract_e(touch_payload.data_raw[i]);

        /* Set event type based on received data */
        switch (event)
        {
            case FT5X06_DOWN:
            case FT5X06_CONTACT:
                s_touch_data.point[i].event = LV_INDEV_STATE_PRESSED;
                break;
            case FT5X06_UP:
            case FT5X06_NO_EVENT:
            default:
                s_touch_data.point[i].event = LV_INDEV_STATE_RELEASED;
                break;
        }
    }

    /*
     * Report the first touch point to LVGL.
     * Only report coordinates when the point is pressed.
     *
     * Reference: reference_projects/lv_port_renesas_ek_ra8p1/src/port/lv_port_indev.c:331-337
     */
    data->state = s_touch_data.point[0].event;
    if (LV_INDEV_STATE_PRESSED == s_touch_data.point[0].event)
    {
        data->point.x = s_touch_data.point[0].x;
        data->point.y = s_touch_data.point[0].y;
    }

    /* Update diagnostic counters */
    s_touch_read_count++;
    s_last_touch_state = data->state;
    if (LV_INDEV_STATE_PRESSED == data->state)
    {
        s_last_touch_x = (int16_t)data->point.x;
        s_last_touch_y = (int16_t)data->point.y;
    }
}

/**********************************************************************************************************************
 NT-Shell command implementation
 *********************************************************************************************************************/

/**
 * "touch status" sub-command handler
 *
 * @details Displays touch panel initialization state, operating mode,
 *          and diagnostic counters.
 */
static void touch_cmd_status(void)
{
    char buf[TOUCH_PRINT_BUF_SIZE];
    const char *status_str;

    switch (s_touch_status) {
        case TOUCH_STATUS_INITIALIZED:
            status_str = "Initialized";
            break;
        case TOUCH_STATUS_ERROR:
            status_str = "ERROR";
            break;
        default:
            status_str = "Not initialized";
            break;
    }

    print_to_console("[Touch Panel Status]\r\n");

    snprintf(buf, sizeof(buf), "  Status       : %s\r\n", status_str);
    print_to_console(buf);

    snprintf(buf, sizeof(buf), "  Mode         : %s\r\n",
             INDEV_EVENT_DRIVEN ? "Event-driven" : "Polling (IRQ-triggered)");
    print_to_console(buf);

    snprintf(buf, sizeof(buf), "  LVGL indev   : %s\r\n",
             (s_indev_touchpad != NULL) ? "Registered" : "Not registered");
    print_to_console(buf);

    snprintf(buf, sizeof(buf), "  Read count   : %lu\r\n",
             (unsigned long)s_touch_read_count);
    print_to_console(buf);

    /* Issue #46: if Read count stays put while this climbs, the I2C transfer
     * is never being attempted because the shared IIC1 bus lock could not be
     * taken (see touchpad_get_xy). Bus ready reflects i2c_bus0_open_once(). */
    snprintf(buf, sizeof(buf), "  Lock fails   : %lu (last err=0x%lX), bus %s\r\n",
             (unsigned long)s_touch_lock_fail_count,
             (unsigned long)s_touch_last_lock_err,
             i2c_bus0_is_ready() ? "open" : "NOT open");
    print_to_console(buf);

    snprintf(buf, sizeof(buf), "  Xfer fails   : %lu (last err=0x%lX)\r\n",
             (unsigned long)s_touch_xfer_fail_count,
             (unsigned long)s_touch_last_xfer_err);
    print_to_console(buf);

    snprintf(buf, sizeof(buf), "  Last state   : %s\r\n",
             (s_last_touch_state == LV_INDEV_STATE_PRESSED) ? "PRESSED" : "RELEASED");
    print_to_console(buf);

    if (s_last_touch_x >= 0 && s_last_touch_y >= 0) {
        snprintf(buf, sizeof(buf), "  Last coord   : (%d, %d)\r\n",
                 s_last_touch_x, s_last_touch_y);
        print_to_console(buf);
    } else {
        print_to_console("  Last coord   : (no touch recorded)\r\n");
    }
}

/**
 * "touch info" sub-command handler
 *
 * @details Displays touch controller hardware information.
 */
static void touch_cmd_info(void)
{
    char buf[TOUCH_PRINT_BUF_SIZE];

    print_to_console("[Touch Controller Information]\r\n");
    print_to_console("  Controller   : GT911 (FT5X06-compatible)\r\n");
    print_to_console("  Interface    : I2C\r\n");

    snprintf(buf, sizeof(buf), "  I2C Address  : 0x38\r\n");
    print_to_console(buf);

    snprintf(buf, sizeof(buf), "  IRQ Channel  : %d (falling edge)\r\n", TOUCH_IRQ_CHANNEL);
    print_to_console(buf);

    snprintf(buf, sizeof(buf), "  Max Points   : %d\r\n", FT5X06_NUM_POINTS);
    print_to_console(buf);

    print_to_console("  Resolution   : 1024 x 600 (matches LCD)\r\n");

    print_to_console("[Register Map]\r\n");

    snprintf(buf, sizeof(buf), "  TD_STATUS    : 0x%02X (touch count)\r\n",
             FT5X06_REG_TD_STATUS);
    print_to_console(buf);

    snprintf(buf, sizeof(buf), "  Payload size : %u bytes\r\n",
             (unsigned int)sizeof(ft5x06_payload_t));
    print_to_console(buf);
}

/**
 * "touch read" sub-command handler
 *
 * @details Performs a single touch data read and displays the result.
 *          This reads directly from I2C regardless of the IRQ state.
 */
static void touch_cmd_read(void)
{
    char buf[TOUCH_PRINT_BUF_SIZE];

    if (s_touch_status != TOUCH_STATUS_INITIALIZED) {
        print_to_console("  Error: Touch panel is not initialized.\r\n");
        return;
    }

    print_to_console("[Touch Read (single)]\r\n");

    /* Perform a direct read */
    lv_indev_data_t data;
    data.state = LV_INDEV_STATE_RELEASED;
    data.point.x = 0;
    data.point.y = 0;

    touchpad_get_xy(&data);

    snprintf(buf, sizeof(buf), "  State  : %s\r\n",
             (data.state == LV_INDEV_STATE_PRESSED) ? "PRESSED" : "RELEASED");
    print_to_console(buf);

    snprintf(buf, sizeof(buf), "  Coord  : (%ld, %ld)\r\n",
             (long)data.point.x, (long)data.point.y);
    print_to_console(buf);

    /* Raw register bytes as they came off the bus (see s_touch_raw). */
    if (s_touch_raw_valid) {
        print_to_console("  Raw    :");
        for (uint32_t i = 0; i < sizeof(s_touch_raw); i++) {
            snprintf(buf, sizeof(buf), " %02X", (unsigned)s_touch_raw[i]);
            print_to_console(buf);
        }
        print_to_console("\r\n");
    } else {
        print_to_console("  Raw    : (no transfer completed)\r\n");
    }

    /* Show all active points from the last read */
    for (uint8_t i = 0; i < FT5X06_NUM_POINTS; i++) {
        if (s_touch_data.point[i].event == LV_INDEV_STATE_PRESSED) {
            snprintf(buf, sizeof(buf), "  Point[%d]: (%u, %u) PRESSED\r\n",
                     i, s_touch_data.point[i].x, s_touch_data.point[i].y);
            print_to_console(buf);
        }
    }
}

/**
 * "touch mon" sub-command handler
 *
 * @details Monitors touch events for a specified duration (default: 5 seconds).
 *          Displays coordinates and state changes in real-time.
 *
 * @param argc  Argument count
 * @param argv  Argument vector (argv[2] = duration in seconds)
 */
static void touch_cmd_mon(int argc, char **argv)
{
    char buf[TOUCH_PRINT_BUF_SIZE];
    uint32_t duration_sec = 5;

    if (s_touch_status != TOUCH_STATUS_INITIALIZED) {
        print_to_console("  Error: Touch panel is not initialized.\r\n");
        return;
    }

    /* Parse optional duration argument */
    if (argc >= 3) {
        cmd_parse_result_t result = cmd_parse_uint32(argv[2]);
        if (result.valid && result.value > 0 && result.value <= 60) {
            duration_sec = result.value;
        } else {
            print_to_console("  Duration must be 1-60 seconds.\r\n");
            return;
        }
    }

    snprintf(buf, sizeof(buf), "[Touch Monitor - %lu seconds (press Ctrl+C to stop)]\r\n",
             (unsigned long)duration_sec);
    print_to_console(buf);

    uint32_t start_count = s_touch_read_count;
    lv_indev_state_t prev_state = LV_INDEV_STATE_RELEASED;

    for (uint32_t elapsed = 0; elapsed < duration_sec * 10; elapsed++) {
        /* Check current state (updated by LVGL thread) */
        lv_indev_state_t current_state = s_last_touch_state;
        int16_t x = s_last_touch_x;
        int16_t y = s_last_touch_y;

        /* Report state changes */
        if (current_state != prev_state) {
            if (current_state == LV_INDEV_STATE_PRESSED) {
                snprintf(buf, sizeof(buf), "  [%lu.%lus] PRESSED  (%d, %d)\r\n",
                         (unsigned long)(elapsed / 10),
                         (unsigned long)(elapsed % 10),
                         x, y);
                print_to_console(buf);
            } else {
                snprintf(buf, sizeof(buf), "  [%lu.%lus] RELEASED\r\n",
                         (unsigned long)(elapsed / 10),
                         (unsigned long)(elapsed % 10));
                print_to_console(buf);
            }
            prev_state = current_state;
        }
        else if (current_state == LV_INDEV_STATE_PRESSED) {
            /* Periodic position update while pressed (every 500ms) */
            if ((elapsed % 5) == 0) {
                snprintf(buf, sizeof(buf), "  [%lu.%lus] CONTACT  (%d, %d)\r\n",
                         (unsigned long)(elapsed / 10),
                         (unsigned long)(elapsed % 10),
                         x, y);
                print_to_console(buf);
            }
        }

        tk_dly_tsk(100);    /* R-006: vTaskDelay(pdMS_TO_TICKS(100)) -> tk_dly_tsk(100) ms */
    }

    uint32_t total_reads = s_touch_read_count - start_count;
    snprintf(buf, sizeof(buf), "  Monitor complete. %lu touch reads during %lu seconds.\r\n",
             (unsigned long)total_reads, (unsigned long)duration_sec);
    print_to_console(buf);
}

/**
 * NT-Shell "touch" command handler
 *
 * @details Provides touch panel diagnostic sub-commands.
 *
 * Reference: lv_port_indev.h (usrcmd_touch declaration)
 */
int usrcmd_touch(int argc, char **argv)
{
    if (argc < 2) {
        cmd_print_usage("touch", "<subcommand>");
        print_to_console("  status - Show touch panel initialization state\r\n");
        print_to_console("  info   - Show touch controller information\r\n");
        print_to_console("  read   - Read current touch data once\r\n");
        print_to_console("  mon    - Monitor touch events: mon [seconds]\r\n");
        return CMD_ERR_USAGE;
    }

    if (ntlibc_strcmp(argv[1], "status") == 0) {
        touch_cmd_status();
        return CMD_OK;
    }

    if (ntlibc_strcmp(argv[1], "info") == 0) {
        touch_cmd_info();
        return CMD_OK;
    }

    if (ntlibc_strcmp(argv[1], "read") == 0) {
        touch_cmd_read();
        return CMD_OK;
    }

    if (ntlibc_strcmp(argv[1], "mon") == 0) {
        touch_cmd_mon(argc, argv);
        return CMD_OK;
    }

    /* Unknown sub-command */
    {
        char buf[TOUCH_PRINT_BUF_SIZE];
        snprintf(buf, sizeof(buf), "Error: Unknown sub-command '%s'.\r\n", argv[1]);
        print_to_console(buf);
    }

    cmd_print_usage("touch", "<subcommand>");
    print_to_console("  status - Show touch panel initialization state\r\n");
    print_to_console("  info   - Show touch controller information\r\n");
    print_to_console("  read   - Read current touch data once\r\n");
    print_to_console("  mon    - Monitor touch events: mon [seconds]\r\n");

    return CMD_ERR_INVALID_ARG;
}
