/**
 * @file lv_port_indev.c
 * @brief Touch panel input device port layer implementation
 * @details
 * Implements the GT911/FT5X06-compatible touch panel driver for LVGL on the
 * EK-RA8P1 Parallel Graphics Expansion Board. Reads touch coordinates via I2C
 * and reports them to LVGL as pointer input events.
 *
 * This module provides:
 *   - Touch panel initialization (I2C open, IRQ enable, LVGL indev create)
 *   - Periodic touch data reading via LVGL indev callback
 *   - Touch IRQ callback for event-driven notification
 *   - I2C communication callback for async transfer completion
 *   - NT-Shell "touch" command for diagnostics
 *
 * I2C Communication Flow:
 *   1. touchpad_read() callback is called by LVGL periodically
 *   2. Checks g_irq_binary_semaphore to detect new touch events
 *   3. If touch detected, sends I2C write-read to register 0x02 (TD_STATUS)
 *   4. RM_COMMS_I2C_WriteRead() sends register address, then reads payload
 *   5. comms_i2c_callback() signals g_i2c_event_group on transfer complete
 *   6. i2c_wait() blocks until transfer completes or times out
 *   7. Touch data is parsed and reported to LVGL
 *
 * Reference:
 *   - reference_projects/lv_port_renesas_ek_ra8p1/src/port/lv_port_indev.c (entire file)
 *   - reference_projects/lv_port_renesas_ek_ra8p1/src/port/lv_port_indev.h
 *   - reference_projects/lv_port_renesas_ek_ra8p1/ra_gen/new_thread0.h:14-24
 *   - reference_projects/lv_port_renesas_ek_ra8p1/ra_gen/new_thread0.c:17-36
 *
 * @note
 * This file is part of the touch panel control (F-001-5) implementation.
 *
 * @note
 * IMPORTANT: This module requires FSP configuration for I2C and External IRQ
 * (Issue #3). Until the FSP modules are added to configuration.xml, this file
 * will not compile. The required FSP instances are documented in
 * lv_port_indev.h and in the "FSP Configuration Required" section below.
 */

/**********************************************************************************************************************
 Includes   <System Includes> , "Project Includes"
 *********************************************************************************************************************/
#include <stdio.h>
#include <string.h>

#include "lv_port_indev.h"
#include "lvgl_thread.h"
#include "jlink_console.h"
#include "cmd_utils.h"
#include "ntlibc.h"

#include "FreeRTOS.h"
#include "task.h"
#include "semphr.h"
#include "event_groups.h"
#include "timers.h"

/*
 * FSP-generated headers for I2C and External IRQ
 *
 * These headers are generated by FSP when the I2C Communication Device
 * (rm_comms_i2c) and External IRQ (r_icu) modules are added to the
 * lvgl_thread in configuration.xml.
 *
 * Until Issue #3 (FSP configuration for I2C/IRQ) is completed,
 * these includes will cause compilation errors. This is intentional -
 * the touch panel driver cannot function without the underlying
 * I2C and IRQ hardware drivers.
 *
 * Required FSP modules (to be added to lvgl_thread):
 *   - I2C Communication Device (rm_comms_i2c): g_comms_i2c_device0
 *   - I2C Shared Bus (rm_comms_i2c): g_comms_i2c_bus0
 *   - I2C Master (r_iic_master): IIC1
 *   - External IRQ (r_icu): g_external_irq0, channel 19
 *   - FreeRTOS Event Group: g_i2c_event_group
 *   - FreeRTOS Binary Semaphore: g_irq_binary_semaphore
 *
 * Reference: reference_projects/lv_port_renesas_ek_ra8p1/ra_gen/new_thread0.h:14-15
 */
#include "rm_comms_i2c.h"
#include "rm_comms_api.h"

/**********************************************************************************************************************
 Macro definitions
 *********************************************************************************************************************/

/** Console output buffer size */
#define TOUCH_PRINT_BUF_SIZE    (128)

/**
 * Maximum number of simultaneous touch points supported by FT5X06/GT911
 *
 * Reference: reference_projects/lv_port_renesas_ek_ra8p1/src/port/lv_port_indev.c:7
 */
#define FT5X06_NUM_POINTS       (5)

/**
 * FT5X06 touch event types
 *
 * Reference: reference_projects/lv_port_renesas_ek_ra8p1/src/port/lv_port_indev.c:9-12
 */
#define FT5X06_DOWN             (0)
#define FT5X06_UP               (1)
#define FT5X06_CONTACT          (2)
#define FT5X06_NO_EVENT         (3)

/**
 * FT5X06 register addresses
 *
 * TD_STATUS (0x02): Contains the number of active touch points in bits [3:0].
 * Followed by 5 sets of touch point data (6 bytes each).
 *
 * Reference: reference_projects/lv_port_renesas_ek_ra8p1/src/port/lv_port_indev.c:14
 */
#define FT5X06_REG_TD_STATUS    (0x02)

/**
 * I2C transfer event flags for EventGroup notification
 *
 * Reference: reference_projects/lv_port_renesas_ek_ra8p1/src/port/lv_port_indev.c:17-18
 */
#define I2C_TRANSFER_COMPLETE   (1 << 0)
#define I2C_TRANSFER_ABORT      (1 << 1)

/**
 * I2C transfer timeout in FreeRTOS ticks
 *
 * Reference: reference_projects/lv_port_renesas_ek_ra8p1/src/port/lv_port_indev.c:20
 */
#define I2C_TIMEOUT_MS          (1000 / portTICK_PERIOD_MS)

/**
 * External IRQ channel number for touch panel INT pin
 *
 * The GT911 touch controller INT pin is connected to IRQ19 on the
 * EK-RA8P1 Parallel Graphics Expansion Board.
 *
 * Reference: reference_projects/lv_port_renesas_ek_ra8p1/src/port/lv_port_indev.c:157
 * Reference: reference_projects/lv_port_renesas_ek_ra8p1/configuration.xml:532
 */
#define TOUCH_IRQ_CHANNEL       (19)

/**********************************************************************************************************************
 Global Typedef definitions
 *********************************************************************************************************************/

/**
 * FT5X06/GT911 raw touch point data structure (6 bytes per point)
 *
 * Bit field layout:
 *   Byte 0: [7:6] event (DOWN/UP/CONTACT/NO_EVENT), [5:4] reserved, [3:0] x_msb
 *   Byte 1: [7:0] x_lsb
 *   Byte 2: [7:4] id (touch point ID), [3:0] y_msb
 *   Byte 3: [7:0] y_lsb
 *   Byte 4: reserved
 *   Byte 5: reserved
 *
 * Reference: reference_projects/lv_port_renesas_ek_ra8p1/src/port/lv_port_indev.c:22-35
 */
typedef struct st_ft5x06_touch
{
    uint8_t  x_msb : 4;
    uint8_t        : 2;
    uint8_t  event : 2;
    uint8_t  x_lsb;

    uint8_t  y_msb : 4;
    uint8_t  id    : 4;
    uint8_t  y_lsb : 8;

    uint8_t  res1;
    uint8_t  res2;
} ft5x06_touch_t;

/**
 * Complete FT5X06 data payload (number of active points + all five touch points)
 *
 * Reference: reference_projects/lv_port_renesas_ek_ra8p1/src/port/lv_port_indev.c:38-42
 */
typedef struct st_ft5x06_payload
{
    uint8_t        num_points_active;
    ft5x06_touch_t data_raw[FT5X06_NUM_POINTS];
} ft5x06_payload_t;

/**
 * Parsed touch coordinate with LVGL event state
 *
 * Reference: reference_projects/lv_port_renesas_ek_ra8p1/src/port/lv_port_indev.c:45-50
 */
typedef struct st_touch_coord
{
    uint16_t         x;
    uint16_t         y;
    lv_indev_state_t event;
} touch_coord_t;

/**
 * Parsed touch data for all points
 *
 * Reference: reference_projects/lv_port_renesas_ek_ra8p1/src/port/lv_port_indev.c:52-56
 */
typedef struct st_touch_data
{
    uint8_t       num_points;
    touch_coord_t point[FT5X06_NUM_POINTS];
} touch_data_t;

/**
 * Touch panel initialization status
 */
typedef enum {
    TOUCH_STATUS_NOT_INITIALIZED = 0,   /**< Not yet initialized */
    TOUCH_STATUS_INITIALIZED,           /**< Successfully initialized */
    TOUCH_STATUS_ERROR,                 /**< Initialization failed */
} touch_status_t;

/**********************************************************************************************************************
 Macro functions
 *********************************************************************************************************************/

/**
 * Extract event, x-coordinate, and y-coordinate from raw touch data
 *
 * Reference: reference_projects/lv_port_renesas_ek_ra8p1/src/port/lv_port_indev.c:58-60
 */
#define extract_e(t)    ((uint8_t)  ((t).event))
#define extract_x(t)    ((int16_t)  (((t).x_msb << 8) | ((t).x_lsb)))
#define extract_y(t)    ((int16_t)  (((t).y_msb << 8) | ((t).y_lsb)))

/**********************************************************************************************************************
 Private (static) functions prototypes
 *********************************************************************************************************************/

/**
 * LVGL touchpad read callback
 *
 * Called by LVGL periodically to poll for touch input.
 * In polling mode, checks the IRQ semaphore first.
 * In event-driven mode, reads touch data directly.
 *
 * Reference: reference_projects/lv_port_renesas_ek_ra8p1/src/port/lv_port_indev.c:246-273
 */
static void touchpad_read(lv_indev_t *indev, lv_indev_data_t *data);

/**
 * Wait for I2C transfer completion using FreeRTOS EventGroup
 *
 * Reference: reference_projects/lv_port_renesas_ek_ra8p1/src/port/lv_port_indev.c:199-225
 */
static fsp_err_t i2c_wait(void);

/**
 * Check if a touch event is pending (polling mode)
 *
 * Reference: reference_projects/lv_port_renesas_ek_ra8p1/src/port/lv_port_indev.c:227-239
 */
static bool touchpad_is_pressed(void);

/**
 * Read touch coordinates from the FT5X06/GT911 controller via I2C
 *
 * Reference: reference_projects/lv_port_renesas_ek_ra8p1/src/port/lv_port_indev.c:275-338
 */
static void touchpad_get_xy(lv_indev_data_t *data);

/* NT-Shell sub-command handlers */
static void touch_cmd_status(void);
static void touch_cmd_info(void);
static void touch_cmd_read(void);
static void touch_cmd_mon(int argc, char **argv);

/**********************************************************************************************************************
 Private (static) variables
 *********************************************************************************************************************/

/** LVGL input device handle */
static lv_indev_t *s_indev_touchpad = NULL;

/**
 * Global touch data (latest parsed result)
 *
 * Reference: reference_projects/lv_port_renesas_ek_ra8p1/src/port/lv_port_indev.c:62
 */
static touch_data_t s_touch_data;

/** Touch panel initialization status */
static touch_status_t s_touch_status = TOUCH_STATUS_NOT_INITIALIZED;

/** Touch event counter (incremented on each touch read) */
static volatile uint32_t s_touch_read_count = 0;

/** Last touch x/y for diagnostics */
static volatile int16_t s_last_touch_x = -1;
static volatile int16_t s_last_touch_y = -1;

/** Last touch state for diagnostics */
static volatile lv_indev_state_t s_last_touch_state = LV_INDEV_STATE_RELEASED;

/**********************************************************************************************************************
 Exported global functions (callbacks called from FSP-generated code)
 *********************************************************************************************************************/

/**
 * Touch panel external IRQ callback
 *
 * @details Called from the ICU external interrupt handler when the GT911
 *          touch controller asserts the INT pin (falling edge on IRQ19).
 *          Gives the IRQ binary semaphore to notify the LVGL thread that
 *          new touch data is available.
 *
 *          This function name must match the callback configured in FSP:
 *            External IRQ -> g_external_irq0 -> Callback: touch_irq_callback
 *
 * @note This function runs in ISR context. Only ISR-safe FreeRTOS APIs
 *       (xSemaphoreGiveFromISR, portYIELD_FROM_ISR) may be used.
 *
 * Reference: reference_projects/lv_port_renesas_ek_ra8p1/src/port/lv_port_indev.c:155-167
 *
 * @param p_args  External IRQ callback arguments (contains channel number)
 */
void touch_irq_callback(external_irq_callback_args_t *p_args)
{
    if (TOUCH_IRQ_CHANNEL == p_args->channel)
    {
        BaseType_t xHigherPriorityTaskWoken = pdFALSE;

        /*
         * Give the IRQ binary semaphore to notify touchpad_is_pressed()
         * that new touch data is available for reading.
         *
         * Reference: reference_projects/lv_port_renesas_ek_ra8p1/src/port/lv_port_indev.c:159-166
         */
        xSemaphoreGiveFromISR(g_irq_binary_semaphore, &xHigherPriorityTaskWoken);

        portYIELD_FROM_ISR(xHigherPriorityTaskWoken);
    }
}

/**
 * I2C communication callback
 *
 * @details Called from the RM_COMMS_I2C driver when an I2C transfer
 *          completes (successfully or with error). Sets the appropriate
 *          bit in g_i2c_event_group to unblock i2c_wait().
 *
 *          This function name must match the callback configured in FSP:
 *            I2C Communication Device -> g_comms_i2c_device0 -> Callback: comms_i2c_callback
 *
 * @note This function runs in ISR context. Only ISR-safe FreeRTOS APIs
 *       (xEventGroupSetBitsFromISR, portYIELD_FROM_ISR) may be used.
 *
 * Reference: reference_projects/lv_port_renesas_ek_ra8p1/src/port/lv_port_indev.c:169-197
 *
 * @param p_args  I2C callback arguments (contains event type)
 */
void comms_i2c_callback(rm_comms_callback_args_t *p_args)
{
    BaseType_t xHigherPriorityTaskWoken = pdFALSE;
    BaseType_t xResult = pdFAIL;

    if (RM_COMMS_EVENT_OPERATION_COMPLETE == p_args->event)
    {
        xResult = xEventGroupSetBitsFromISR(g_i2c_event_group,
                                            I2C_TRANSFER_COMPLETE,
                                            &xHigherPriorityTaskWoken);
    }
    else if (RM_COMMS_EVENT_ERROR == p_args->event)
    {
        xResult = xEventGroupSetBitsFromISR(g_i2c_event_group,
                                            I2C_TRANSFER_ABORT,
                                            &xHigherPriorityTaskWoken);
    }
    else
    {
        /* Should never get here */
    }

    if (pdFAIL != xResult)
    {
        /*
         * If xHigherPriorityTaskWoken is now set to pdTRUE then a context
         * switch should be requested.
         *
         * Reference: reference_projects/lv_port_renesas_ek_ra8p1/src/port/lv_port_indev.c:188-195
         */
        portYIELD_FROM_ISR(xHigherPriorityTaskWoken);
    }
}

/**********************************************************************************************************************
 Exported global functions
 *********************************************************************************************************************/

/**
 * Initialize the touch panel input device
 *
 * Reference: reference_projects/lv_port_renesas_ek_ra8p1/src/port/lv_port_indev.c:95-149
 */
void lv_port_indev_init(void)
{
    fsp_err_t err;

    /*
     * Step 1: Create and register LVGL input device
     *
     * Create a pointer-type input device and register the touchpad_read
     * callback. LVGL will call this callback periodically to check for
     * new touch events.
     *
     * Reference: reference_projects/lv_port_renesas_ek_ra8p1/src/port/lv_port_indev.c:104-106
     */
    s_indev_touchpad = lv_indev_create();
    lv_indev_set_type(s_indev_touchpad, LV_INDEV_TYPE_POINTER);
    lv_indev_set_read_cb(s_indev_touchpad, touchpad_read);

#if (1 == INDEV_EVENT_DRIVEN)
    /* Update the input device's running mode to LV_INDEV_MODE_EVENT */
    lv_indev_set_mode(s_indev_touchpad, LV_INDEV_MODE_EVENT);
#endif

    /*
     * Step 2: Open the I2C bus driver
     *
     * Access the underlying I2C master driver through the RM_COMMS_I2C
     * configuration's extended configuration. The I2C master must be
     * opened before the communication device can be used.
     *
     * Reference: reference_projects/lv_port_renesas_ek_ra8p1/src/port/lv_port_indev.c:115-119
     */
    rm_comms_i2c_bus_extended_cfg_t *p_extend =
        (rm_comms_i2c_bus_extended_cfg_t *)g_comms_i2c_device0_cfg.p_extend;
    i2c_master_instance_t *p_driver_instance =
        (i2c_master_instance_t *)p_extend->p_driver_instance;

    err = p_driver_instance->p_api->open(p_driver_instance->p_ctrl,
                                          p_driver_instance->p_cfg);
    assert(FSP_SUCCESS == err);

    /*
     * Step 3: Create FreeRTOS synchronization objects for I2C bus
     *
     * The RM_COMMS_I2C bus requires:
     *   - A counting semaphore (initial count 0) for blocking on bus operations
     *   - A recursive mutex for bus lock (allows nested I2C transactions)
     *
     * These are created here rather than in the FSP-generated code because
     * the FreeRTOS static allocation functions need to be called at runtime.
     *
     * Reference: reference_projects/lv_port_renesas_ek_ra8p1/src/port/lv_port_indev.c:121-138
     */
#if (2 == BSP_CFG_RTOS)
    /* Create a semaphore for blocking if a semaphore is not NULL */
    if (NULL != p_extend->p_blocking_semaphore)
    {
        *(p_extend->p_blocking_semaphore->p_semaphore_handle) =
            xSemaphoreCreateCountingStatic((UBaseType_t)1,
                                           (UBaseType_t)0,
                                           p_extend->p_blocking_semaphore->p_semaphore_memory);
    }
    /* Create a recursive mutex for bus lock if a recursive mutex is not NULL */
    if (NULL != p_extend->p_bus_recursive_mutex)
    {
        *(p_extend->p_bus_recursive_mutex->p_mutex_handle) =
            xSemaphoreCreateRecursiveMutexStatic(p_extend->p_bus_recursive_mutex->p_mutex_memory);
    }
#endif

    /*
     * Step 4: Open the I2C communication device
     *
     * RM_COMMS_I2C_Open() configures the I2C device with the slave address
     * (0x38 for GT911/FT5X06) and communication parameters.
     *
     * Note: The LCD reset (performed in glcdc_port_init) is shared with
     * the touch controller. The touch controller must be initialized
     * after the LCD reset sequence.
     *
     * Reference: reference_projects/lv_port_renesas_ek_ra8p1/src/port/lv_port_indev.c:141-142
     */
    err = RM_COMMS_I2C_Open(&g_comms_i2c_device0_ctrl, &g_comms_i2c_device0_cfg);
    assert(FSP_SUCCESS == err);

    /*
     * Step 5: Open and enable external IRQ for touch events
     *
     * The GT911 INT pin generates a falling-edge interrupt when new
     * touch data is available. The IRQ callback (touch_irq_callback)
     * gives the g_irq_binary_semaphore to notify the LVGL thread.
     *
     * Reference: reference_projects/lv_port_renesas_ek_ra8p1/src/port/lv_port_indev.c:144-148
     */
    err = R_ICU_ExternalIrqOpen(&g_external_irq0_ctrl, &g_external_irq0_cfg);
    assert(FSP_SUCCESS == err);

    err = R_ICU_ExternalIrqEnable(&g_external_irq0_ctrl);
    assert(FSP_SUCCESS == err);

    s_touch_status = TOUCH_STATUS_INITIALIZED;
}

/**
 * Get the LVGL input device handle
 */
lv_indev_t *lv_port_indev_get(void)
{
    return s_indev_touchpad;
}

/**********************************************************************************************************************
 Private (static) functions
 *********************************************************************************************************************/

/**
 * Wait for I2C transfer completion
 *
 * @details Blocks on g_i2c_event_group until either the transfer completes
 *          successfully, aborts with error, or times out.
 *
 * Reference: reference_projects/lv_port_renesas_ek_ra8p1/src/port/lv_port_indev.c:199-225
 *
 * @retval FSP_SUCCESS       Transfer completed successfully
 * @retval FSP_ERR_ABORTED   Transfer aborted due to I2C error
 * @retval FSP_ERR_TIMEOUT   Transfer timed out
 */
static fsp_err_t i2c_wait(void)
{
    fsp_err_t ret = FSP_SUCCESS;
    EventBits_t uxBits;

    uxBits = xEventGroupWaitBits(g_i2c_event_group,
                                 I2C_TRANSFER_COMPLETE | I2C_TRANSFER_ABORT,
                                 pdTRUE,    /* Clear bits before returning */
                                 pdFALSE,   /* Either bit will do */
                                 I2C_TIMEOUT_MS);

    if ((I2C_TRANSFER_COMPLETE & uxBits) == I2C_TRANSFER_COMPLETE)
    {
        ret = FSP_SUCCESS;
    }
    else if ((I2C_TRANSFER_ABORT & uxBits) == I2C_TRANSFER_ABORT)
    {
        ret = FSP_ERR_ABORTED;
    }
    else
    {
        /* xEventGroupWaitBits() returned because of timeout */
        ret = FSP_ERR_TIMEOUT;
    }

    return ret;
}

/**
 * Check if a touch event is pending
 *
 * @details Attempts to take the g_irq_binary_semaphore with zero timeout
 *          (non-blocking). Returns true if the semaphore was available,
 *          indicating that touch_irq_callback() was called since the last check.
 *
 * Reference: reference_projects/lv_port_renesas_ek_ra8p1/src/port/lv_port_indev.c:227-239
 *
 * @retval true   Touch event is pending (semaphore was taken)
 * @retval false  No touch event pending
 */
static bool touchpad_is_pressed(void)
{
    BaseType_t status;
    bool touch_pressed = false;

    status = xSemaphoreTake(g_irq_binary_semaphore, 0);
    if (pdTRUE == status)
    {
        touch_pressed = true;
    }

    return touch_pressed;
}

/**
 * LVGL touchpad read callback
 *
 * @details Called by LVGL periodically to poll for touch input.
 *
 * In polling mode (INDEV_EVENT_DRIVEN == 0):
 *   - First checks if a touch event is pending via touchpad_is_pressed()
 *   - If pending, reads touch data via I2C
 *   - If not pending, returns the last known state and coordinates
 *   - This minimizes I2C bus traffic by only reading when touch IRQ fires
 *
 * In event-driven mode (INDEV_EVENT_DRIVEN == 1):
 *   - Reads touch data directly on every LVGL poll
 *
 * Reference: reference_projects/lv_port_renesas_ek_ra8p1/src/port/lv_port_indev.c:246-273
 *
 * @param indev  LVGL input device handle (unused)
 * @param data   Output: touch state and coordinates
 */
static void touchpad_read(lv_indev_t *indev, lv_indev_data_t *data)
{
    FSP_PARAMETER_NOT_USED(indev);

    data->state = LV_INDEV_STATE_RELEASED;

#if (1 == INDEV_EVENT_DRIVEN)
    touchpad_get_xy(data);
#else
    /*
     * Polling mode: Save the pressed coordinates and the state.
     * Only perform I2C read when the IRQ semaphore indicates new data.
     *
     * Reference: reference_projects/lv_port_renesas_ek_ra8p1/src/port/lv_port_indev.c:256-271
     */
    static lv_indev_state_t last_state = LV_INDEV_STATE_RELEASED;
    static lv_point_t last_point = {.x = 0, .y = 0};

    if (touchpad_is_pressed()) {
        touchpad_get_xy(data);
        last_state = data->state;
        last_point.x = data->point.x;
        last_point.y = data->point.y;
    }
    else
    {
        data->state   = last_state;
        data->point.x = last_point.x;
        data->point.y = last_point.y;
    }
#endif
}

/**
 * Read touch coordinates from the FT5X06/GT911 controller
 *
 * @details Performs an I2C write-read transaction to read the touch status
 *          register (0x02) and all five touch point data sets. Parses the
 *          raw bit-field data into x/y coordinates and event types.
 *
 *          I2C transaction:
 *            Write: 1 byte (register address 0x02)
 *            Read:  31 bytes (1 byte status + 5 x 6 bytes touch data)
 *
 *          Only the first touch point is reported to LVGL (single-touch).
 *          Multi-touch data is parsed but not used by LVGL's pointer model.
 *
 * Reference: reference_projects/lv_port_renesas_ek_ra8p1/src/port/lv_port_indev.c:275-338
 *
 * @param data  Output: touch state and coordinates for LVGL
 */
static void touchpad_get_xy(lv_indev_data_t *data)
{
    fsp_err_t err;
    rm_comms_write_read_params_t write_read_params;
    ft5x06_payload_t touch_payload;
    uint8_t event;
    uint8_t reg;
    uint8_t touch_count;

    reg = FT5X06_REG_TD_STATUS;

    write_read_params.src_bytes  = 1;
    write_read_params.p_src      = &reg;
    write_read_params.p_dest     = (uint8_t *)&touch_payload;
    write_read_params.dest_bytes = sizeof(ft5x06_payload_t);

    /*
     * Write TD_STATUS address, then read status + all five touch point registers.
     *
     * Reference: reference_projects/lv_port_renesas_ek_ra8p1/src/port/lv_port_indev.c:293-294
     */
    err = RM_COMMS_I2C_WriteRead(&g_comms_i2c_device0_ctrl, write_read_params);
    assert(FSP_SUCCESS == err);

    err = i2c_wait();
    assert(FSP_SUCCESS == err);

    /* Extract active touch count from lower nibble */
    touch_count = touch_payload.num_points_active & 0x0F;

    if (FT5X06_NUM_POINTS < touch_count)
    {
        /* Invalid touch count - should not happen */
        assert(0);
    }

    /* Reset all points to released before parsing new data */
    for (uint8_t i = 0; i < FT5X06_NUM_POINTS; i++)
    {
        s_touch_data.point[i].event = LV_INDEV_STATE_RELEASED;
    }

    /*
     * Process the raw data for the touch point(s) into useful coordinates.
     *
     * Reference: reference_projects/lv_port_renesas_ek_ra8p1/src/port/lv_port_indev.c:310-329
     */
    for (uint8_t i = 0; i < touch_count; i++)
    {
        s_touch_data.point[i].x = (uint16_t)extract_x(touch_payload.data_raw[i]);
        s_touch_data.point[i].y = (uint16_t)extract_y(touch_payload.data_raw[i]);
        event                   = extract_e(touch_payload.data_raw[i]);

        /* Set event type based on received data */
        switch (event)
        {
            case FT5X06_DOWN:
            case FT5X06_CONTACT:
                s_touch_data.point[i].event = LV_INDEV_STATE_PRESSED;
                break;
            case FT5X06_UP:
            case FT5X06_NO_EVENT:
            default:
                s_touch_data.point[i].event = LV_INDEV_STATE_RELEASED;
                break;
        }
    }

    /*
     * Report the first touch point to LVGL.
     * Only report coordinates when the point is pressed.
     *
     * Reference: reference_projects/lv_port_renesas_ek_ra8p1/src/port/lv_port_indev.c:331-337
     */
    data->state = s_touch_data.point[0].event;
    if (LV_INDEV_STATE_PRESSED == s_touch_data.point[0].event)
    {
        data->point.x = s_touch_data.point[0].x;
        data->point.y = s_touch_data.point[0].y;
    }

    /* Update diagnostic counters */
    s_touch_read_count++;
    s_last_touch_state = data->state;
    if (LV_INDEV_STATE_PRESSED == data->state)
    {
        s_last_touch_x = (int16_t)data->point.x;
        s_last_touch_y = (int16_t)data->point.y;
    }
}

/**********************************************************************************************************************
 NT-Shell command implementation
 *********************************************************************************************************************/

/**
 * "touch status" sub-command handler
 *
 * @details Displays touch panel initialization state, operating mode,
 *          and diagnostic counters.
 */
static void touch_cmd_status(void)
{
    char buf[TOUCH_PRINT_BUF_SIZE];
    const char *status_str;

    switch (s_touch_status) {
        case TOUCH_STATUS_INITIALIZED:
            status_str = "Initialized";
            break;
        case TOUCH_STATUS_ERROR:
            status_str = "ERROR";
            break;
        default:
            status_str = "Not initialized";
            break;
    }

    print_to_console("[Touch Panel Status]\r\n");

    snprintf(buf, sizeof(buf), "  Status       : %s\r\n", status_str);
    print_to_console(buf);

    snprintf(buf, sizeof(buf), "  Mode         : %s\r\n",
             INDEV_EVENT_DRIVEN ? "Event-driven" : "Polling (IRQ-triggered)");
    print_to_console(buf);

    snprintf(buf, sizeof(buf), "  LVGL indev   : %s\r\n",
             (s_indev_touchpad != NULL) ? "Registered" : "Not registered");
    print_to_console(buf);

    snprintf(buf, sizeof(buf), "  Read count   : %lu\r\n",
             (unsigned long)s_touch_read_count);
    print_to_console(buf);

    snprintf(buf, sizeof(buf), "  Last state   : %s\r\n",
             (s_last_touch_state == LV_INDEV_STATE_PRESSED) ? "PRESSED" : "RELEASED");
    print_to_console(buf);

    if (s_last_touch_x >= 0 && s_last_touch_y >= 0) {
        snprintf(buf, sizeof(buf), "  Last coord   : (%d, %d)\r\n",
                 s_last_touch_x, s_last_touch_y);
        print_to_console(buf);
    } else {
        print_to_console("  Last coord   : (no touch recorded)\r\n");
    }
}

/**
 * "touch info" sub-command handler
 *
 * @details Displays touch controller hardware information.
 */
static void touch_cmd_info(void)
{
    char buf[TOUCH_PRINT_BUF_SIZE];

    print_to_console("[Touch Controller Information]\r\n");
    print_to_console("  Controller   : GT911 (FT5X06-compatible)\r\n");
    print_to_console("  Interface    : I2C\r\n");

    snprintf(buf, sizeof(buf), "  I2C Address  : 0x38\r\n");
    print_to_console(buf);

    snprintf(buf, sizeof(buf), "  IRQ Channel  : %d (falling edge)\r\n", TOUCH_IRQ_CHANNEL);
    print_to_console(buf);

    snprintf(buf, sizeof(buf), "  Max Points   : %d\r\n", FT5X06_NUM_POINTS);
    print_to_console(buf);

    print_to_console("  Resolution   : 1024 x 600 (matches LCD)\r\n");

    print_to_console("[Register Map]\r\n");

    snprintf(buf, sizeof(buf), "  TD_STATUS    : 0x%02X (touch count)\r\n",
             FT5X06_REG_TD_STATUS);
    print_to_console(buf);

    snprintf(buf, sizeof(buf), "  Payload size : %u bytes\r\n",
             (unsigned int)sizeof(ft5x06_payload_t));
    print_to_console(buf);
}

/**
 * "touch read" sub-command handler
 *
 * @details Performs a single touch data read and displays the result.
 *          This reads directly from I2C regardless of the IRQ state.
 */
static void touch_cmd_read(void)
{
    char buf[TOUCH_PRINT_BUF_SIZE];

    if (s_touch_status != TOUCH_STATUS_INITIALIZED) {
        print_to_console("  Error: Touch panel is not initialized.\r\n");
        return;
    }

    print_to_console("[Touch Read (single)]\r\n");

    /* Perform a direct read */
    lv_indev_data_t data;
    data.state = LV_INDEV_STATE_RELEASED;
    data.point.x = 0;
    data.point.y = 0;

    touchpad_get_xy(&data);

    snprintf(buf, sizeof(buf), "  State  : %s\r\n",
             (data.state == LV_INDEV_STATE_PRESSED) ? "PRESSED" : "RELEASED");
    print_to_console(buf);

    snprintf(buf, sizeof(buf), "  Coord  : (%ld, %ld)\r\n",
             (long)data.point.x, (long)data.point.y);
    print_to_console(buf);

    /* Show all active points from the last read */
    for (uint8_t i = 0; i < FT5X06_NUM_POINTS; i++) {
        if (s_touch_data.point[i].event == LV_INDEV_STATE_PRESSED) {
            snprintf(buf, sizeof(buf), "  Point[%d]: (%u, %u) PRESSED\r\n",
                     i, s_touch_data.point[i].x, s_touch_data.point[i].y);
            print_to_console(buf);
        }
    }
}

/**
 * "touch mon" sub-command handler
 *
 * @details Monitors touch events for a specified duration (default: 5 seconds).
 *          Displays coordinates and state changes in real-time.
 *
 * @param argc  Argument count
 * @param argv  Argument vector (argv[2] = duration in seconds)
 */
static void touch_cmd_mon(int argc, char **argv)
{
    char buf[TOUCH_PRINT_BUF_SIZE];
    uint32_t duration_sec = 5;

    if (s_touch_status != TOUCH_STATUS_INITIALIZED) {
        print_to_console("  Error: Touch panel is not initialized.\r\n");
        return;
    }

    /* Parse optional duration argument */
    if (argc >= 3) {
        cmd_parse_result_t result = cmd_parse_uint32(argv[2]);
        if (result.valid && result.value > 0 && result.value <= 60) {
            duration_sec = result.value;
        } else {
            print_to_console("  Duration must be 1-60 seconds.\r\n");
            return;
        }
    }

    snprintf(buf, sizeof(buf), "[Touch Monitor - %lu seconds (press Ctrl+C to stop)]\r\n",
             (unsigned long)duration_sec);
    print_to_console(buf);

    uint32_t start_count = s_touch_read_count;
    lv_indev_state_t prev_state = LV_INDEV_STATE_RELEASED;

    for (uint32_t elapsed = 0; elapsed < duration_sec * 10; elapsed++) {
        /* Check current state (updated by LVGL thread) */
        lv_indev_state_t current_state = s_last_touch_state;
        int16_t x = s_last_touch_x;
        int16_t y = s_last_touch_y;

        /* Report state changes */
        if (current_state != prev_state) {
            if (current_state == LV_INDEV_STATE_PRESSED) {
                snprintf(buf, sizeof(buf), "  [%lu.%lus] PRESSED  (%d, %d)\r\n",
                         (unsigned long)(elapsed / 10),
                         (unsigned long)(elapsed % 10),
                         x, y);
                print_to_console(buf);
            } else {
                snprintf(buf, sizeof(buf), "  [%lu.%lus] RELEASED\r\n",
                         (unsigned long)(elapsed / 10),
                         (unsigned long)(elapsed % 10));
                print_to_console(buf);
            }
            prev_state = current_state;
        }
        else if (current_state == LV_INDEV_STATE_PRESSED) {
            /* Periodic position update while pressed (every 500ms) */
            if ((elapsed % 5) == 0) {
                snprintf(buf, sizeof(buf), "  [%lu.%lus] CONTACT  (%d, %d)\r\n",
                         (unsigned long)(elapsed / 10),
                         (unsigned long)(elapsed % 10),
                         x, y);
                print_to_console(buf);
            }
        }

        vTaskDelay(pdMS_TO_TICKS(100));
    }

    uint32_t total_reads = s_touch_read_count - start_count;
    snprintf(buf, sizeof(buf), "  Monitor complete. %lu touch reads during %lu seconds.\r\n",
             (unsigned long)total_reads, (unsigned long)duration_sec);
    print_to_console(buf);
}

/**
 * NT-Shell "touch" command handler
 *
 * @details Provides touch panel diagnostic sub-commands.
 *
 * Reference: lv_port_indev.h (usrcmd_touch declaration)
 */
int usrcmd_touch(int argc, char **argv)
{
    if (argc < 2) {
        cmd_print_usage("touch", "<subcommand>");
        print_to_console("  status - Show touch panel initialization state\r\n");
        print_to_console("  info   - Show touch controller information\r\n");
        print_to_console("  read   - Read current touch data once\r\n");
        print_to_console("  mon    - Monitor touch events: mon [seconds]\r\n");
        return CMD_ERR_USAGE;
    }

    if (ntlibc_strcmp(argv[1], "status") == 0) {
        touch_cmd_status();
        return CMD_OK;
    }

    if (ntlibc_strcmp(argv[1], "info") == 0) {
        touch_cmd_info();
        return CMD_OK;
    }

    if (ntlibc_strcmp(argv[1], "read") == 0) {
        touch_cmd_read();
        return CMD_OK;
    }

    if (ntlibc_strcmp(argv[1], "mon") == 0) {
        touch_cmd_mon(argc, argv);
        return CMD_OK;
    }

    /* Unknown sub-command */
    {
        char buf[TOUCH_PRINT_BUF_SIZE];
        snprintf(buf, sizeof(buf), "Error: Unknown sub-command '%s'.\r\n", argv[1]);
        print_to_console(buf);
    }

    cmd_print_usage("touch", "<subcommand>");
    print_to_console("  status - Show touch panel initialization state\r\n");
    print_to_console("  info   - Show touch controller information\r\n");
    print_to_console("  read   - Read current touch data once\r\n");
    print_to_console("  mon    - Monitor touch events: mon [seconds]\r\n");

    return CMD_ERR_INVALID_ARG;
}
