/**
 * @file lvgl_port_mtk3.h
 * @brief uT-Kernel 3.0 replacement for the FSP RM_LVGL_PORT module (R-006 / Issue #156)
 * @details
 * RM_LVGL_PORT (ra/fsp/src/rm_lvgl_port/rm_lvgl_port.c - read-only) calls
 * FreeRTOS blocking APIs (`xSemaphoreTake(portMAX_DELAY)` in the flush-wait
 * callback, `xSemaphoreGiveFromISR` in the Vsync ISR, `xTaskGetTickCount()`
 * for the LVGL tick) when `BSP_CFG_RTOS == 2`, which the migration policy kept
 * up to Issue #186 Step 2. Under boot method A the FreeRTOS scheduler never
 * starts, so these calls would hang or fault.
 *
 * Issue #186 Step 2 set the FSP RTOS selection to "No RTOS"
 * (`BSP_CFG_RTOS == 0`), so rm_lvgl_port.c now compiles its bare-metal path
 * instead. This module stays in use regardless: it is what actually drives the
 * display (Vsync semaphore, flush wait, tick), and `RM_LVGL_PORT_Open()` is
 * still never called.
 *
 * This module BYPASSES RM_LVGL_PORT instead of editing it:
 *   - `lvgl_port_mtk3_open()` re-implements `RM_LVGL_PORT_Open()` 1:1 but
 *     copies the FSP-generated display cfg (`g_display0_cfg`) and swaps only
 *     the display callback, so `ra_gen/` stays untouched and no build
 *     exclusion is needed (`RM_LVGL_PORT_Open` / `_rm_lvgl_port_display_callback`
 *     remain linked but are never executed).
 *   - Vsync synchronization uses a uT-Kernel binary semaphore
 *     (tk_cre_sem maxsem=1 / tk_sig_sem from ISR / two-step tk_wai_sem).
 *   - The LVGL millisecond tick uses tk_get_otm() (same technique as
 *     camera_framebuffer.c in R-005).
 *
 * The FSP-generated `g_lvgl_port_cfg` (ra_gen/common_data.c) is reused
 * read-only, so framebuffer names/sizes regenerated by FSP are followed
 * automatically. The user callback registered there (`lvgl_glcdc_callback`
 * in glcdc_port.c - Vsync/underflow statistics) keeps working: this module
 * performs the same event conversion as `_rm_lvgl_port_display_callback`
 * before forwarding.
 *
 * Design reference: doc/migration/r006a-lvgl-osal-spike.md 5.4
 * Original: e2studio_CPU0/ra/fsp/src/rm_lvgl_port/rm_lvgl_port.c
 */

#ifndef LVGL_PORT_MTK3_H
#define LVGL_PORT_MTK3_H

#include "rm_lvgl_port.h"   /* rm_lvgl_port_cfg_t / rm_lvgl_port_callback_args_t (types only) */
#include "lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Open the display port (uT-Kernel version of RM_LVGL_PORT_Open).
 *
 * Performs, in the same order as RM_LVGL_PORT_Open (rm_lvgl_port.c:82-171):
 *   1. Vsync semaphore creation (uT-Kernel, maxsem=1)
 *   2. Framebuffer clear (memset of fb 0/1)
 *   3. R_GLCDC_Open() with a COPY of the display cfg (callback swapped)
 *   4. R_GLCDC_Start()
 *   5. R_GLCDC_BufferChange() to display framebuffer 1 (double buffering)
 *   6. lv_display_create() + flush/flush-wait callback registration
 *   7. lv_display_set_buffers_with_stride() (DIRECT render mode)
 *   8. lv_tick_set_cb() (tk_get_otm based ms tick)
 *
 * @param p_cfg  FSP-generated LVGL port configuration (&g_lvgl_port_cfg)
 * @retval FSP_SUCCESS            opened successfully
 * @retval FSP_ERR_ASSERTION      p_cfg is NULL
 * @retval FSP_ERR_OUT_OF_MEMORY  lv_display_create() or semaphore creation failed
 * @return other R_GLCDC_Open/Start/BufferChange error codes
 */
fsp_err_t lvgl_port_mtk3_open(rm_lvgl_port_cfg_t const *p_cfg);

/**
 * Get the LVGL display object created by lvgl_port_mtk3_open().
 *
 * Replaces references to `g_lvgl_port_ctrl.p_lv_display`.
 *
 * @return LVGL display pointer, or NULL if not opened
 */
lv_display_t *lvgl_port_mtk3_get_display(void);

#ifdef __cplusplus
}
#endif

#endif /* LVGL_PORT_MTK3_H */
